# Generated by Django 2.2.7 on 2019-11-09 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title tag')),
                ('key', models.CharField(blank=True, db_index=True, default='', help_text='Key is used in the code, do not modify it', max_length=70, verbose_name='key')),
                ('url', models.CharField(help_text='Page full path: /news/ or /', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^/([a-z0-9-_A-Z]+/)*', message='Must start and end with slash')], verbose_name='url')),
                ('text', models.TextField(blank=True, help_text='HTML content of the page if it is static', null=True, verbose_name='text')),
                ('published', models.BooleanField(db_index=True, default=False, help_text='The page will not be shown at the site until it is published', verbose_name='published')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='meta keywords')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='staticpages.Page', verbose_name='parent page')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140, null=True, verbose_name='title')),
                ('image', models.FileField(upload_to='staticpages', verbose_name='image')),
                ('position', models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='position')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='staticpages.Page')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140, null=True, verbose_name='name')),
                ('file', models.FileField(upload_to='staticpages', verbose_name='file')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='staticpages.Page')),
            ],
        ),
    ]
