# Generated by Django 2.2.7 on 2019-11-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='wide_view',
            field=models.BooleanField(default=True, verbose_name='wide view mode'),
        ),
    ]
