# Generated by Django 2.2.7 on 2019-11-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0002_page_wide_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='container',
            field=models.BooleanField(default=0, help_text='Check if this is a container page for child pages.', verbose_name='container for child pages'),
        ),
    ]
