# Generated by Django 2.2.7 on 2019-11-20 10:13

from django.db import migrations, models
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0003_page_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='staticpages/svg', validators=[stroykerbox.apps.utils.validators.validator_svg], verbose_name='icon (svg)'),
        ),
    ]
