# Generated by Django 2.2.8 on 2019-12-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0004_page_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date and time of update'),
        ),
    ]
