# Generated by Django 2.2.11 on 2020-04-07 10:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0005_page_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='HTML content of the page if it is static', null=True, verbose_name='text'),
        ),
    ]
