# Generated by Django 2.2.19 on 2021-03-06 16:06

from django.db import migrations, models
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0006_auto_20200407_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='teaser_image',
            field=models.FileField(blank=True, null=True, upload_to='staticpages/images', validators=[stroykerbox.apps.utils.validators.validate_svg_or_image], verbose_name='teaser image'),
        ),
    ]
