# Generated by Django 2.2.20 on 2021-08-23 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0007_page_teaser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='no_wrapper',
            field=models.BooleanField(default=False, help_text='Use the html-code of the page as is, without using a wrapper.', verbose_name='don`t use wrapper'),
        ),
        migrations.CreateModel(
            name='PageCustomStaticfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='staticpages/custom_staticfiles/', verbose_name='file')),
                ('file_type', models.CharField(blank=True, max_length=4, null=True, verbose_name='file type')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_staticfiles', to='staticpages.Page')),
            ],
            options={
                'verbose_name': 'page custom staticfile',
                'verbose_name_plural': 'page custom staticfiles',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PageCustomCss',
            fields=[
            ],
            options={
                'verbose_name': 'custom css file',
                'verbose_name_plural': 'custom css files',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('staticpages.pagecustomstaticfile',),
        ),
        migrations.CreateModel(
            name='PageCustomJs',
            fields=[
            ],
            options={
                'verbose_name': 'custom js file',
                'verbose_name_plural': 'custom js files',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('staticpages.pagecustomstaticfile',),
        ),
    ]
