# Generated by Django 2.2.26 on 2022-02-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_auto_20220204_1507'),
        ('staticpages', '0008_auto_20210823_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='related_productset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ProductSet', verbose_name='related product set'),
        ),
    ]
