# Generated by Django 3.2.15 on 2023-04-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0011_pagecontructor_pagecontructorblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontructor',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='pagecontructor',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='meta keywords'),
        ),
    ]
