# Generated by Django 3.2.15 on 2023-04-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0012_auto_20230406_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontructor',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='position'),
        ),
        migrations.CreateModel(
            name='PageParendBreadcrumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title tag')),
                ('link', models.CharField(max_length=255, verbose_name='link')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breadcrumbs', to='staticpages.pagecontructor')),
            ],
            options={
                'verbose_name': 'page parent breadcrumb',
                'verbose_name_plural': 'page parent breadcrumbs',
                'ordering': ['position'],
            },
        ),
    ]
