# Generated by Django 2.2.20 on 2021-07-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('published', models.BooleanField(default=True, verbose_name='published')),
                ('frontpage', models.BooleanField(default=False, verbose_name='show on frontpage')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['position'],
            },
        ),
    ]
