# Generated by Django 2.2.20 on 2021-07-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='opened',
            field=models.BooleanField(default=False, verbose_name='opened'),
        ),
    ]
