# Generated by Django 2.2.9 on 2020-02-21 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0023_auto_20200221_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.PositiveSmallIntegerField(choices=[(0, 'no rating'), (1, 'very bad'), (2, 'bad'), (3, 'satisfactory'), (4, 'well'), (5, 'very well')], default=0, verbose_name='rating')),
                ('review_text', models.TextField(blank=True, null=True, verbose_name='review text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.Product', verbose_name='имя')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product review',
                'verbose_name_plural': 'product reviews',
                'ordering': ['-rating_value', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReviewHelpfulness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(verbose_name='review is helpful')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_helpfulness', to='reviews.ProductReview')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_helpful_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('review', 'user')},
            },
        ),
    ]
