# Generated by Django 2.2.12 on 2020-10-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200221_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-rating_value', '-created_at'], 'verbose_name': 'отзыв о товаре', 'verbose_name_plural': 'отзывы о товаре'},
        ),
        migrations.AlterField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='published',
            field=models.BooleanField(default=False, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating_value',
            field=models.PositiveSmallIntegerField(choices=[(0, 'нет оценок'), (1, 'очень плохо'), (2, 'плохо'), (3, 'удовлетворительно'), (4, 'хорошо'), (5, 'очень хорошо')], default=0, verbose_name='оценка'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_text',
            field=models.TextField(blank=True, null=True, verbose_name='текст отзыва'),
        ),
        migrations.AlterField(
            model_name='productreviewhelpfulness',
            name='is_helpful',
            field=models.BooleanField(verbose_name='отзыв полезен'),
        ),
    ]
