# Generated by Django 2.2.12 on 2020-10-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-created_at',), 'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
    ]
