FROM dalay/python:3.10-slim

ENV PYTHONUNBUFFERED 1

# Dependencies for WeasyPrint 50 on Debian/Ubuntu (https://weasyprint.readthedocs.io/en/stable/install.html#linux):
# build-essential python3-dev python3-pip python3-setuptools python3-wheel python3-cffi libcairo2 
# libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
# libz-dev libjpeg-dev libfreetype6-dev && \ # for django-simple-captcha
RUN apt-get update && \
    apt-get install -y gettext gcc git \
    build-essential python3-dev python3-cffi libcairo2 \
    libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info \
    libz-dev libjpeg-dev libfreetype6-dev pipenv python3-distutils && \
    apt-get clean && \
    mkdir /code /pip-src && \
    rm -rf /var/lib/apt/lists/*

COPY ./Pipfile* /code/

WORKDIR /code

ENV PIP_SRC=/pip-src

RUN export PIPENV_CACHE_DIR=/pipenv_cache \
    && mkdir $PIPENV_CACHE_DIR \
    && pip install --disable-pip-version-check --no-cache-dir uwsgi \
    && pipenv install --system \
    && rm -rf $PIPENV_CACHE_DIR
