# Generated by Django 2.2.9 on 2019-12-30 11:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0004_auto_20191227_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='имя')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^7[\\d]{10}$', 'Enter a valid phone number starting with "7" followed by 10 digits.', 'invalid')], verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='email')),
                ('geo_latitude', models.DecimalField(decimal_places=6, help_text='latitude of the partner location', max_digits=9, verbose_name='latitude')),
                ('geo_longitude', models.DecimalField(decimal_places=6, help_text='longitude of the partner location', max_digits=9, verbose_name='longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('slug', models.SlugField(null=True, verbose_name='название-метка (Для URL)')),
                ('website', models.URLField(verbose_name='site url')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses_partner_related', related_query_name='addresses_partners', to='locations.Location', verbose_name='location')),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partners',
            },
        ),
    ]
