# Generated by Django 2.2.9 on 2019-12-30 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'default_related_name': 'contacts', 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'default_related_name': 'partners', 'verbose_name': 'partner', 'verbose_name_plural': 'partners'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='locations.Location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='locations.Location', verbose_name='location'),
        ),
    ]
