# Generated by Django 2.2.11 on 2020-03-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20191230_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'default_related_name': 'contacts', 'ordering': ('-position',), 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AddField(
            model_name='contact',
            name='extra',
            field=models.TextField(blank=True, null=True, verbose_name='extra info'),
        ),
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=64, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=models.SlugField(null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='slug',
            field=models.SlugField(null=True, verbose_name='slug'),
        ),
    ]
