# Generated by Django 2.2.12 on 2020-10-13 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20200318_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'default_related_name': 'contacts', 'ordering': ('position',), 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[78][\\d]{10}$', 'Enter a valid phone number starting with "7 (or 8)" followed by 10 digits.', 'invalid')], verbose_name='phone'),
        ),
    ]
