# Generated by Django 2.2.19 on 2021-03-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_auto_20201013_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
