# Generated by Django 2.2.26 on 2022-02-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0007_auto_20210728_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ymap_glyph_color',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('red', 'red'), ('darkOrange', 'dark orange'), ('night', 'night'), ('darkBlue', 'dark blue'), ('pink', 'pink'), ('gray', 'gray'), ('brown', 'brown'), ('darkGreen', 'dark green'), ('violet', 'violet'), ('black', 'black'), ('yellow', 'yellow'), ('green', 'green'), ('orange', 'orange'), ('lightBlue', 'light blue'), ('olive', 'olive')], max_length=16, null=True, verbose_name='glyph icon color'),
        ),
        migrations.AddField(
            model_name='contact',
            name='ymap_glyph_icon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='glyph icon name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='ymap_icon_color',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('red', 'red'), ('darkOrange', 'dark orange'), ('night', 'night'), ('darkBlue', 'dark blue'), ('pink', 'pink'), ('gray', 'gray'), ('brown', 'brown'), ('darkGreen', 'dark green'), ('violet', 'violet'), ('black', 'black'), ('yellow', 'yellow'), ('green', 'green'), ('orange', 'orange'), ('lightBlue', 'light blue'), ('olive', 'olive')], max_length=16, null=True, verbose_name='icon color'),
        ),
        migrations.AddField(
            model_name='partner',
            name='ymap_glyph_color',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('red', 'red'), ('darkOrange', 'dark orange'), ('night', 'night'), ('darkBlue', 'dark blue'), ('pink', 'pink'), ('gray', 'gray'), ('brown', 'brown'), ('darkGreen', 'dark green'), ('violet', 'violet'), ('black', 'black'), ('yellow', 'yellow'), ('green', 'green'), ('orange', 'orange'), ('lightBlue', 'light blue'), ('olive', 'olive')], max_length=16, null=True, verbose_name='glyph icon color'),
        ),
        migrations.AddField(
            model_name='partner',
            name='ymap_glyph_icon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='glyph icon name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='ymap_icon_color',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('red', 'red'), ('darkOrange', 'dark orange'), ('night', 'night'), ('darkBlue', 'dark blue'), ('pink', 'pink'), ('gray', 'gray'), ('brown', 'brown'), ('darkGreen', 'dark green'), ('violet', 'violet'), ('black', 'black'), ('yellow', 'yellow'), ('green', 'green'), ('orange', 'orange'), ('lightBlue', 'light blue'), ('olive', 'olive')], max_length=16, null=True, verbose_name='icon color'),
        ),
    ]
