# Generated by Django 2.2.26 on 2022-02-10 10:08

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0008_auto_20220209_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ymap_glyph_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='glyph icon color'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='ymap_glyph_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='glyph icon color'),
        ),
    ]
