# Generated by Django 3.2.25 on 2025-06-20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0010_auto_20250611_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='позиция')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'категория партнера',
                'verbose_name_plural': 'категории партнеров',
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='page_url',
            field=models.CharField(blank=True, help_text='Внутренняя ссылка на страницу партнера, если такая есть.', max_length=255, null=True, validators=[django.core.validators.RegexValidator('^/([a-z0-9-_A-Z]+/)*', message='Внутренний URL должен начинаться и заканчиваться слешем.')], verbose_name='страница партнера'),
        ),
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='addresses.partnercategory', verbose_name='категория'),
        ),
    ]
