# Generated by Django 3.2.25 on 2025-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0011_auto_20250620_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=60, verbose_name='name'),
        ),
    ]
