# Generated by Django 3.2.25

from django.db import migrations, models
import django.db.models.deletion


def migrate_coordinates(apps, *args, **kwargs):
    Partner = apps.get_model('addresses', 'Partner')
    PartnerCoordinates = apps.get_model('addresses', 'PartnerCoordinates')
    for p in Partner.objects.all():
        coordinates = f'{p.geo_latitude},{p.geo_longitude}'
        PartnerCoordinates.objects.create(partner=p, coordinates=coordinates)


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0012_alter_partner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCoordinates',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'coordinates',
                    models.CharField(
                        help_text='Ввод через запятую, последовательность обязательна: сначала - широта, затем - долгота.',
                        max_length=32,
                        verbose_name='широта/долгота',
                    ),
                ),
                (
                    'partner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='coordinates',
                        to='addresses.partner',
                    ),
                ),
            ],
            options={
                'verbose_name': 'координаты партнера',
                'verbose_name_plural': 'координаты партнера',
            },
        ),

        migrations.RunPython(migrate_coordinates, migrations.RunPython.noop),

        migrations.RemoveField(
            model_name='partner',
            name='geo_latitude',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='geo_longitude',
        ),
    ]
