# Generated by Django 3.2.25 on 2025-09-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0013_multiple_partner_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='позиция')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'город партнера',
                'verbose_name_plural': 'города партнеров',
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='addresses.partnercity', verbose_name='город'),
        ),
    ]
