# Generated by Django 2.2.7 on 2019-12-05 11:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('image', models.ImageField(upload_to='bnr_images', verbose_name='image')),
                ('image_url', models.CharField(blank=True, help_text='Target url when the image desplays as a link.', max_length=255, null=True, verbose_name='image target url')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date of publication')),
                ('end_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='end date of publication')),
                ('advertiser_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='advertiser email')),
                ('clicks_counter', models.PositiveIntegerField(default=0, editable=False, verbose_name='number of clicks on the banner')),
                ('views_counter', models.PositiveIntegerField(default=0, editable=False, verbose_name='number of banner views')),
            ],
        ),
        migrations.CreateModel(
            name='BannerDisplayUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=256, validators=[django.core.validators.RegexValidator('^/([\\w=&/?-]+)*$', message='must start and end with a slash (/)')], verbose_name='relative url')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_urls', to='banners.Banner', verbose_name='banner')),
            ],
            options={
                'unique_together': {('banner', 'url')},
            },
        ),
    ]
