# Generated by Django 2.2.7 on 2019-12-05 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='renewal_notice_date',
            field=models.DateField(blank=True, editable=False, help_text='The date the advertiser was last notified of the extension of his banner.The value is entered automatically.', null=True, verbose_name='renewal notice date'),
        ),
        migrations.AlterField(
            model_name='bannerdisplayurl',
            name='url',
            field=models.CharField(db_index=True, max_length=256, validators=[django.core.validators.RegexValidator('^(/([\\w=&/?-]+)*)?/$', message='must start and end with a slash (/)')], verbose_name='relative url'),
        ),
    ]
