# Generated by Django 2.2.7 on 2019-12-06 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20191205_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='This value is used in the code. Do not touch it!', max_length=70, unique=True, verbose_name='key')),
                ('title', models.CharField(max_length=255, verbose_name='block title')),
                ('published', models.BooleanField(db_index=True, default=True, verbose_name='published')),
            ],
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='bnrs/images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='position'),
        ),
        migrations.CreateModel(
            name='BannerSetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='banner title')),
                ('image', models.ImageField(upload_to='bnrs/set_images', verbose_name='image')),
                ('image_url', models.CharField(blank=True, help_text='Target url when the image desplays as a link.', max_length=255, null=True, verbose_name='image target url')),
                ('content', models.TextField(blank=True, help_text='Content of the banner', null=True, verbose_name='content')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='banners.BannerSet')),
            ],
        ),
    ]
