# Generated by Django 2.2.7 on 2019-12-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_auto_20191206_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'banner', 'verbose_name_plural': 'banners'},
        ),
        migrations.AlterModelOptions(
            name='bannerset',
            options={'verbose_name': 'banner set', 'verbose_name_plural': 'banner sets'},
        ),
        migrations.AlterModelOptions(
            name='bannersetitem',
            options={'verbose_name': 'banner set item', 'verbose_name_plural': 'banner set items'},
        ),
    ]
