# Generated by Django 2.2.7 on 2019-12-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_auto_20191206_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerset',
            name='key',
            field=models.SlugField(help_text='This value is used in the code. Do not touch it!', max_length=70, unique=True, verbose_name='key'),
        ),
    ]
