# Generated by Django 2.2.11 on 2020-03-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_auto_20191206_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannersetitem',
            options={'ordering': ['position'], 'verbose_name': 'banner set item', 'verbose_name_plural': 'banner set items'},
        ),
        migrations.AddField(
            model_name='banner',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='bnrs/images/svg', verbose_name='svg image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bnrs/images', verbose_name='image'),
        ),
    ]
