# Generated by Django 2.2.11 on 2020-03-31 11:44

from django.db import migrations, models
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0006_auto_20200331_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='bnrs/images/svg', validators=[stroykerbox.apps.utils.validators.validator_svg], verbose_name='svg image'),
        ),
    ]
