# Generated by Django 2.2.12 on 2020-10-12 15:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0007_auto_20200331_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='StroykerBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bnrs/images', verbose_name='image')),
                ('svg', models.FileField(blank=True, null=True, upload_to='bnrs/images/svg', validators=[stroykerbox.apps.utils.validators.validator_svg], verbose_name='svg image')),
                ('image_url', models.CharField(blank=True, help_text='Target url when the image desplays as a link.', max_length=255, null=True, verbose_name='image target url')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date of publication')),
                ('end_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='end date of publication')),
                ('advertiser_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='advertiser email')),
                ('clicks_counter', models.PositiveIntegerField(default=0, editable=False, verbose_name='number of clicks on the banner')),
                ('views_counter', models.PositiveIntegerField(default=0, editable=False, verbose_name='number of banner views')),
                ('renewal_notice_date', models.DateField(blank=True, editable=False, help_text='The date the advertiser was last notified of the extension of his banner.The value is entered automatically.', null=True, verbose_name='renewal notice date')),
            ],
            options={
                'verbose_name': 'stroyker banner',
                'verbose_name_plural': 'stroyker banners',
                'ordering': ['position'],
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['position'], 'verbose_name': 'banner', 'verbose_name_plural': 'banners'},
        ),
        migrations.CreateModel(
            name='StroykerBannerDisplayUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=256, validators=[django.core.validators.RegexValidator('^(/([\\w=&/?-]+)*)?/$', message='must start and end with a slash (/)')], verbose_name='relative url')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_urls_stroyker', to='banners.StroykerBanner', verbose_name='banner')),
            ],
            options={
                'abstract': False,
                'unique_together': {('banner', 'url')},
            },
        ),
    ]
