# Generated by Django 2.2.17 on 2020-12-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0008_auto_20201012_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='all_pages',
            field=models.BooleanField(default=False, verbose_name='show on all pages'),
        ),
        migrations.AddField(
            model_name='stroykerbanner',
            name='all_pages',
            field=models.BooleanField(default=False, verbose_name='show on all pages'),
        ),
    ]
