# Generated by Django 2.2.17 on 2021-03-05 10:54

from django.db import migrations, models
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0009_auto_20201211_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.CharField(blank=True, help_text='Target url when the image desplays as a link.', max_length=255, null=True, validators=[stroykerbox.apps.utils.validators.url_or_path_validator], verbose_name='image target url'),
        ),
        migrations.AlterField(
            model_name='stroykerbanner',
            name='image_url',
            field=models.CharField(blank=True, help_text='Target url when the image desplays as a link.', max_length=255, null=True, validators=[stroykerbox.apps.utils.validators.url_or_path_validator], verbose_name='image target url'),
        ),
    ]
