# Generated by Django 2.2.19 on 2021-03-05 17:59

from django.db import migrations, models
import stroykerbox.apps.utils.validators


def create_new_block_with_three_banner_set(apps, schema_editor):
    BannerSet = apps.get_model('banners', 'BannerSet')
    BannerSet.objects.create(key='frontpage_three_banner_block',
                             title='Блок с 3-ми баннерами на главной',
                             qty=3)

    SliderTagContainer = apps.get_model('customization', 'SliderTagContainer')
    SliderTagContainerItem = apps.get_model(
        'customization', 'SliderTagContainerItem')
    if SliderTagContainer and SliderTagContainerItem:
        container = SliderTagContainer.objects.filter(key='middle').first()
        if container:
            SliderTagContainerItem.objects.create(
                container=container,
                tag_line='banner_tags:render_banner_set',
                args='frontpage_three_banner_block',
                wrapper_classes='banner-items-section',
                enabled=False
            )


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0025_add_wrapper_for_frontpage_seo_text_item'),
        ('banners', '0010_auto_20210305_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerset',
            name='qty',
            field=models.PositiveSmallIntegerField(
                default=3, help_text='Number of banners in a set', verbose_name='banners qty'),
        ),
        migrations.AddField(
            model_name='bannersetitem',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='bnrs/set_images', validators=[
                                   stroykerbox.apps.utils.validators.validator_svg], verbose_name='svg image'),
        ),
        migrations.AlterField(
            model_name='bannersetitem',
            name='image',
            field=models.ImageField(
                blank=True, null=True, upload_to='bnrs/set_images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='bannersetitem',
            name='image_url',
            field=models.CharField(blank=True, help_text='Target url when the image desplays as a link.', max_length=255, null=True, validators=[
                                   stroykerbox.apps.utils.validators.url_or_path_validator], verbose_name='image target url'),
        ),
        migrations.RunPython(create_new_block_with_three_banner_set,)
    ]
