# Generated by Django 2.2.26 on 2022-01-13 21:20

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0011_auto_20210305_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerMultirowSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='This value is used in the code. Do not touch it!', max_length=70, unique=True, verbose_name='key')),
                ('title', models.CharField(max_length=255, verbose_name='block title')),
                ('banners_per_line', models.PositiveSmallIntegerField(choices=[(2, 2), (3, 3)], default=2, verbose_name='banners per line')),
            ],
            options={
                'verbose_name': 'banner multirow set',
                'verbose_name_plural': 'banner multirow sets',
            },
        ),
        migrations.CreateModel(
            name='BannerRowSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_type', models.PositiveSmallIntegerField(choices=[(1, 'as background'), (2, 'as image')], default=1, verbose_name='row display type')),
            ],
            options={
                'verbose_name': 'banner row set',
                'verbose_name_plural': 'banner row sets',
            },
        ),
        migrations.CreateModel(
            name='BannerRowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bnrs/images', verbose_name='image')),
                ('svg', models.FileField(blank=True, null=True, upload_to='bnrs/images/svg', validators=[stroykerbox.apps.utils.validators.validator_svg], verbose_name='svg image')),
                ('image_url', models.CharField(blank=True, help_text='Target url when the image desplays as a link.', max_length=255, null=True, validators=[stroykerbox.apps.utils.validators.url_or_path_validator], verbose_name='image target url')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('name', models.CharField(blank=True, help_text='Used as an alt for the banner image or as a link title when the banner is a link.', max_length=128, null=True, verbose_name='name')),
                ('hide_adaptive', models.BooleanField(default=False, verbose_name='hide in adaptive')),
                ('bg_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='background color')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text content')),
                ('img_open_full', models.BooleanField(default=False, verbose_name='open image in full size')),
                ('rowset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rowset_items', to='banners.BannerRowSet')),
            ],
            options={
                'verbose_name': 'banner row item',
                'verbose_name_plural': 'banner row items',
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BannerMultirowSetRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('multirowset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.BannerMultirowSet')),
                ('rowset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.BannerRowSet')),
            ],
            options={
                'verbose_name': 'multirowset rows membership',
                'verbose_name_plural': 'multirowset rows memberships',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='bannermultirowset',
            name='rowsets',
            field=models.ManyToManyField(through='banners.BannerMultirowSetRows', to='banners.BannerRowSet', verbose_name='row sets'),
        ),
    ]
