# Generated by Django 2.2.26 on 2022-01-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0012_auto_20220114_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerrowset',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='name'),
        ),
    ]
