# Generated by Django 2.2.26 on 2022-02-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0013_bannerrowset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermultirowset',
            name='banners_per_line',
            field=models.PositiveSmallIntegerField(choices=[(2, 2), (3, 3), (4, 4), (6, 6)], default=2, verbose_name='banners per line'),
        ),
    ]
