# Generated by Django 3.2.20 on 2023-09-18 12:02

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0015_auto_20230202_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSetRowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bnrs/images', verbose_name='image')),
                ('svg', models.FileField(blank=True, null=True, upload_to='bnrs/images/svg', validators=[stroykerbox.apps.utils.validators.validator_svg], verbose_name='svg image')),
                ('image_url', models.CharField(blank=True, help_text='Target url when the image desplays as a link.', max_length=255, null=True, validators=[stroykerbox.apps.utils.validators.url_or_path_validator], verbose_name='image target url')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('name', models.CharField(blank=True, help_text='Used as an alt for the banner image or as a link title when the banner is a link.', max_length=128, null=True, verbose_name='name')),
                ('hide_adaptive', models.BooleanField(default=False, verbose_name='hide in adaptive')),
                ('bg_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='background color')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text content')),
                ('img_open_full', models.BooleanField(default=False, verbose_name='open image in full size')),
            ],
            options={
                'verbose_name': 'bannerset item',
                'verbose_name_plural': 'bannerset items',
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bannerset',
            name='qty',
        ),
        migrations.AddField(
            model_name='bannerset',
            name='grid_columns_lg',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='class="grid-colums-lg-VALUE"'),
        ),
        migrations.AddField(
            model_name='bannerset',
            name='grid_columns_md',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='class="grid-colums-md-VALUE"'),
        ),
        migrations.AddField(
            model_name='bannerset',
            name='grid_columns_sm',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='class="grid-colums-sm-VALUE"'),
        ),
        migrations.AddField(
            model_name='bannerset',
            name='row_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'as background'), (2, 'as image')], default=1, verbose_name='тип отображения'),
        ),
        migrations.AlterField(
            model_name='bannerset',
            name='key',
            field=models.SlugField(help_text='Не нужно изменять это значение - оно используется при отображании в шаблоне!', max_length=70, unique=True, verbose_name='ключ'),
        ),
        migrations.AlterField(
            model_name='bannerset',
            name='published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='опубликован'),
        ),
        migrations.AlterField(
            model_name='bannerset',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок набора'),
        ),
        migrations.DeleteModel(
            name='BannerSetItem',
        ),
        migrations.AddField(
            model_name='bannersetrowitem',
            name='rowset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bannerset_items', to='banners.bannerset'),
        ),
    ]
