# Generated by Django 3.2.20 on 2023-09-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0016_auto_20230918_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerset',
            name='grid_columns',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='class="grid-colums-VALUE"'),
        ),
    ]
