# Generated by Django 2.2.7 on 2019-11-19 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiscountGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='group name')),
                ('discount', models.SmallIntegerField(default=0, verbose_name='discount percent')),
            ],
        ),
        migrations.AlterModelOptions(
            name='userdocument',
            options={'ordering': ['-doc_date'], 'verbose_name': 'user document', 'verbose_name_plural': 'user documents'},
        ),
        migrations.AddField(
            model_name='user',
            name='discount_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.UserDiscountGroup', verbose_name='user group'),
        ),
    ]
