# Generated by Django 2.2.7 on 2019-11-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191119_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdiscountgroup',
            options={'verbose_name': 'discount group', 'verbose_name_plural': 'discount groups'},
        ),
        migrations.AlterField(
            model_name='user',
            name='discount_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.UserDiscountGroup', verbose_name='discount group'),
        ),
    ]
