# Generated by Django 2.2.7 on 2019-11-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191119_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_discount',
            field=models.SmallIntegerField(blank=True, help_text='Personal discount for the user. In percents.', null=True, verbose_name='personal discount'),
        ),
    ]
