# Generated by Django 2.2.12 on 2020-10-13 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_personal_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, help_text='Account company name', max_length=60, null=True, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Account`s unique e-mail address. Used as login for authorization.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='Account person name', max_length=60, null=True, verbose_name='contact person'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Account phone number', max_length=11, validators=[django.core.validators.RegexValidator('^[\\d]{11}$', 'Enter a valid phone number of 11 digits.', 'invalid')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='doc_date',
            field=models.DateField(help_text='Document`s date.', verbose_name='document date'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='file',
            field=models.FileField(help_text='Document file.', upload_to='users/documents', verbose_name='document file'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='name',
            field=models.CharField(help_text='Document`s name.', max_length=128, verbose_name='document name'),
        ),
    ]
