# Generated by Django 3.2.25 on 2024-12-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20241210_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Account phone number', max_length=18, null=True, verbose_name='phone'),
        ),
    ]
