# Generated by Django 3.2.25 on 2025-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_personal_manager_only',
            field=models.BooleanField(
                default=False,
                help_text='Отправлять уведомления о заказах только персональному менеджеру.',
                verbose_name='уведомления только менеджеру',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_manager_email',
            field=models.EmailField(
                blank=True,
                help_text='Email менеджера, назначенного пользователю.',
                max_length=254,
                null=True,
                verbose_name='email менеджера',
            ),
        ),
    ]
