# Generated by Django 3.2.25 on 2025-07-31

from django.db import migrations
from django.core.management import call_command


def load_fixtures_with_default_users(apps, schema_editor):
    try:
        User = apps.get_model('users.user')
        if not User.objects.exists():
            call_command('loaddata', 'initial_users.json', app_label='users')
    except Exception:
        return


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20250623_1442'),
    ]

    operations = [
        migrations.RunPython(
            load_fixtures_with_default_users, migrations.RunPython.noop
        ),
    ]
