# Generated by Django 3.2.25 on 2025-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_fix_creation_default_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_info',
            field=models.TextField(blank=True, null=True, verbose_name='персональная информация в ЛК'),
        ),
    ]
