# Generated by Django 3.2.25 on 2025-08-18

from django.db import migrations, models
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_personal_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/', validators=[stroykerbox.apps.utils.validators.validate_svg_or_image], verbose_name='аватар'),
        ),
    ]
