# Generated by Django 2.2.11 on 2020-04-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderTagContainer',
            fields=[
                ('key', models.SlugField(max_length=70, primary_key=True, serialize=False, verbose_name='key')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='SliderTagContainerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_line', models.CharField(help_text='The name of the tag. Which should be called in a template.', max_length=60, verbose_name='tag function name')),
                ('args', models.CharField(help_text='Arguments to pass to the tag when it is called in the template. Comma separated.For example, to pass the key for a slider with a set of products, you must specify this key in this field.', max_length=32, verbose_name='pass args')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='customization.SliderTagContainer')),
            ],
            options={
                'verbose_name': 'template tag',
                'verbose_name_plural': 'template tags',
                'ordering': ['position'],
            },
        ),
    ]
