# Generated by Django 2.2.11 on 2020-04-07 16:38

from django.db import migrations

from stroykerbox.apps.customization import DEFAULT_TAG_CONTAINERS


def create_containers(apps, schema_editor):
    SliderTagContainer = apps.get_model('customization', 'SliderTagContainer')

    for key, name in DEFAULT_TAG_CONTAINERS.items():
        SliderTagContainer.objects.create(key=key, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_containers,)
    ]
