# Generated by Django 2.2.11 on 2020-04-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_main_containers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidertagcontaineritem',
            name='args',
            field=models.CharField(blank=True, help_text='Arguments to pass to the tag when it is called in the template. Comma separated.For example, to pass the key for a slider with a set of products, you must specify this key in this field.', max_length=32, null=True, verbose_name='pass args'),
        ),
        migrations.AlterField(
            model_name='slidertagcontaineritem',
            name='tag_line',
            field=models.CharField(choices=[('catalog_tags:render_bestsellers_slider', 'catalog_tags:render_bestsellers_slider'), ('catalog_tags:render_sales_slider', 'catalog_tags:render_sales_slider'), ('catalog_tags:render_product_images_slider', 'catalog_tags:render_product_images_slider'), ('catalog_tags:render_product_set_slider', 'catalog_tags:render_product_set_slider'), ('news_tags:render_news_slider', 'news_tags:render_news_slider'), ('article_tags:render_articles_slider', 'article_tags:render_articles_slider'), ('slide_tags:render_big_slides', 'slide_tags:render_big_slides'), ('slide_tags:render_partner_slides', 'slide_tags:render_partner_slides')], help_text='The name of the tag. Which should be called in a template.', max_length=60, verbose_name='tag function name'),
        ),
    ]
