# Generated by Django 2.2.12 on 2020-04-09 10:21

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0003_auto_20200407_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('active', models.BooleanField(blank=True, null=True, verbose_name='is active')),
                ('main_elements_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='main elements color')),
                ('main_elements_hover_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='main elements color on hover')),
                ('colorless_buttons_border_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='colorless buttons border color')),
                ('checkout_button_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='checkout button color')),
                ('invoice_button_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='invoice button color')),
                ('header_bg_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='header background color')),
                ('content_bg_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='content area bg color')),
                ('footer_bg_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='footer bg color')),
                ('preview_bg_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='preview bg color')),
                ('preview_bg_hover_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='preview bg color on hover')),
                ('hit_tag_bg_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='hit tag bg color')),
                ('sale_tag_bg_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='sale tag bg color')),
                ('new_tag_bg_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='is new tag bg color')),
                ('news_label_bg_color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='news label bg color')),
            ],
        ),
        migrations.AlterField(
            model_name='slidertagcontaineritem',
            name='tag_line',
            field=models.CharField(choices=[('users_tags:render_user_lk_link', 'users_tags:render_user_lk_link'), ('catalog_tags:render_catalog_categories_menu', 'catalog_tags:render_catalog_categories_menu'), ('catalog_tags:render_catalog_categories_menu_mobile', 'catalog_tags:render_catalog_categories_menu_mobile'), ('catalog_tags:render_catalog_categories_menu_simple', 'catalog_tags:render_catalog_categories_menu_simple'), ('catalog_tags:render_product_availability_status', 'catalog_tags:render_product_availability_status'), ('catalog_tags:render_cart_related_products', 'catalog_tags:render_cart_related_products'), ('catalog_tags:render_catalog_product_teaser', 'catalog_tags:render_catalog_product_teaser'), ('catalog_tags:render_bestsellers_slider', 'catalog_tags:render_bestsellers_slider'), ('catalog_tags:render_sales_slider', 'catalog_tags:render_sales_slider'), ('catalog_tags:render_product_images_slider', 'catalog_tags:render_product_images_slider'), ('catalog_tags:render_product_flags', 'catalog_tags:render_product_flags'), ('catalog_tags:render_product_price_chart', 'catalog_tags:render_product_price_chart'), ('catalog_tags:render_product_documents', 'catalog_tags:render_product_documents'), ('catalog_tags:render_products_list_header', 'catalog_tags:render_products_list_header'), ('catalog_tags:render_catalog_filter', 'catalog_tags:render_catalog_filter'), ('catalog_tags:render_product_properties', 'catalog_tags:render_product_properties'), ('catalog_tags:render_found_cheaper_panel', 'catalog_tags:render_found_cheaper_panel'), ('catalog_tags:render_product_set_slider', 'catalog_tags:render_product_set_slider'), ('catalog_tags:render_related_products', 'catalog_tags:render_related_products'), ('commerce_tags:render_cart', 'commerce_tags:render_cart'), ('commerce_tags:render_commerce_login_form', 'commerce_tags:render_commerce_login_form'), ('utils_tags:render_footer_social_links', 'utils_tags:render_footer_social_links'), ('statictext_tags:render_statictext', 'statictext_tags:render_statictext'), ('news_tags:render_news_teaser', 'news_tags:render_news_teaser'), ('news_tags:render_news_slider', 'news_tags:render_news_slider'), ('news_tags:render_related_news', 'news_tags:render_related_news'), ('menu_tags:render_menu', 'menu_tags:render_menu'), ('crm_tags:render_feedback_message_request_form', 'crm_tags:render_feedback_message_request_form'), ('crm_tags:render_callme_request_form', 'crm_tags:render_callme_request_form'), ('article_tags:render_articles_slider', 'article_tags:render_articles_slider'), ('article_tags:render_related_articles', 'article_tags:render_related_articles'), ('slide_tags:render_big_slides', 'slide_tags:render_big_slides'), ('slide_tags:render_partner_slides', 'slide_tags:render_partner_slides'), ('banner_tags:render_banners', 'banner_tags:render_banners'), ('banner_tags:render_sidebar_banners', 'banner_tags:render_sidebar_banners'), ('banner_tags:render_banner_set', 'banner_tags:render_banner_set'), ('seo_tags:render_meta_tags', 'seo_tags:render_meta_tags'), ('seo_tags:render_breadcrumbs', 'seo_tags:render_breadcrumbs'), ('seo_tags:render_h1', 'seo_tags:render_h1'), ('seo_tags:render_title', 'seo_tags:render_title'), ('location_tags:render_current_location_block', 'location_tags:render_current_location_block'), ('address_tags:render_frontpage_partner_promo_block', 'address_tags:render_frontpage_partner_promo_block'), ('address_tags:render_partners_yamap', 'address_tags:render_partners_yamap'), ('reviews_tags:render_review_form', 'reviews_tags:render_review_form'), ('reviews_tags:render_product_reviews', 'reviews_tags:render_product_reviews'), ('reviews_tags:render_rating_five_stars', 'reviews_tags:render_rating_five_stars'), ('reviews_tags:render_product_average_rating', 'reviews_tags:render_product_average_rating'), ('subscription_tags:render_footer_subscription_form', 'subscription_tags:render_footer_subscription_form'), ('customization_tags:render_tag_container', 'customization_tags:render_tag_container')], help_text='The name of the tag. Which should be called in a template.', max_length=60, verbose_name='tag function name'),
        ),
    ]
