# Generated by Django 2.2.12 on 2020-04-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0004_auto_20200409_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorscheme',
            name='active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
    ]
