# Generated by Django 2.2.12 on 2020-04-10 12:30

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0005_auto_20200409_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='discount_tag_bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='discount tag bg color'),
        ),
        migrations.AlterField(
            model_name='slidertagcontaineritem',
            name='args',
            field=models.CharField(blank=True, help_text='Arguments to pass to the tag when it is called in the template. Comma separated.For example, to pass the key arg for a slider with a set of products, you must specify this key in this field. Only string arguments are supported', max_length=32, null=True, verbose_name='pass args'),
        ),
        migrations.AlterField(
            model_name='slidertagcontaineritem',
            name='tag_line',
            field=models.CharField(help_text='The name of the tag. Which should be called in a template.', max_length=60, verbose_name='tag function name'),
        ),
    ]
