# Generated by Django 2.2.12 on 2020-05-04 12:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0006_auto_20200410_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorscheme',
            options={'verbose_name': 'color scheme', 'verbose_name_plural': 'color schemes'},
        ),
        migrations.AlterModelOptions(
            name='slidertagcontainer',
            options={'verbose_name': 'templatetag container', 'verbose_name_plural': 'templatetag containers'},
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='action_label_bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='action label bg color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='article_label_bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='article label bg color'),
        ),
    ]
