# Generated by Django 2.2.12 on 2020-05-09 12:33

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0007_auto_20200504_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorscheme',
            name='content_bg_color',
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='action_label_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='action label font color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='article_label_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='article label font color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='catalog_menu_bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='catalog menu bg color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='catalog_menu_border_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='catalog menu border color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='catalog_menu_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='catalog menu font color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='catalog_menu_hover_bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='catalog menu nover bg color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='checkout_button_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='checkout button font color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='colorless_buttons_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='colorless buttons font color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='discount_tag_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='discount tag font color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='frontpage_first_screen_bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='frontpage first screen bg color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='header_buttons_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='header buttons font color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='header_top_bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='header top background color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='header_top_menu_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='header top menu font color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='header_top_menu_font_hover_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='header top menu font hover color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='header_top_phone_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='header top phone font color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='hit_tag_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='hit tag font color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='invoice_button_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='invoice button font color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='new_tag_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='is new tag font color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='product_preview_bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='product preview bg color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='sale_tag_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='sale tag font color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='search_field_bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='search field bg color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='search_field_border_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='search field border color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='search_field_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='search field font color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='search_field_placeholder_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='search field placeholder font color'),
        ),
    ]
