# Generated by Django 2.2.12 on 2020-05-09 13:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0008_auto_20200509_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='news_label_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='news label font color'),
        ),
    ]
