# Generated by Django 2.2.12 on 2020-05-18 09:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0009_colorscheme_news_label_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='catalog_menu_arrow_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='catalog menu arrow icon color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='catalog_menu_burger_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='catalog menu burger icon color'),
        ),
    ]
