# Generated by Django 2.2.12 on 2020-05-19 08:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0010_auto_20200518_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='catalog_menu_font_hover_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='catalog menu font hover color'),
        ),
    ]
