# Generated by Django 2.2.12 on 2020-05-19 08:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0011_colorscheme_catalog_menu_font_hover_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='feedback_form_section_bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='bg color for section block with feedback form'),
        ),
    ]
