# Generated by Django 2.2.12 on 2020-05-19 09:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0012_colorscheme_feedback_form_section_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='breadcrumb_sep_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='breadcrumb separator color'),
        ),
    ]
