# Generated by Django 2.2.12 on 2020-05-19 09:24

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0013_colorscheme_breadcrumb_sep_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='breadcrumb_item_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='breadcrumb item color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='breadcrumb_item_hover_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='breadcrumb item color on hover'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='product_list_header_link_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='color for links in product list header'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='product_list_header_link_hover_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='color for links in product list header on hover'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='product_tab_link_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='color for product tab links'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='product_tab_link_hover_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='color for product tab links on hover'),
        ),
    ]
