# Generated by Django 2.2.12 on 2020-05-19 10:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0014_auto_20200519_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='callme_button_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='color for call-me button'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='callme_button_hover_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='color for call-me button on hover'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='product_preview_border_hover_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='product preview border color on hover'),
        ),
    ]
