# Generated by Django 2.2.12 on 2020-05-19 15:44

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0015_auto_20200519_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='callme_button_fill_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='color for call-me button'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='callme_button_fill_hover_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='color for call-me button on hover'),
        ),
    ]
