# Generated by Django 2.2.12 on 2020-08-17 14:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0017_auto_20200817_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='header_top_icon_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='header top icon color'),
        ),
    ]
