# Generated by Django 2.2.12 on 2020-08-17 14:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0018_colorscheme_header_top_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='staticpage_box_border_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='border color for staticpage text box'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='staticpage_box_fill_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='fill color for staticpage text box'),
        ),
    ]
