# Generated by Django 2.2.17 on 2020-11-30 11:08

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0020_auto_20201013_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='colorless_buttons_hover_bg',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='colorless buttons background on hover'),
        ),
    ]
