# Generated by Django 2.2.17 on 2020-11-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0021_colorscheme_colorless_buttons_hover_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidertagcontaineritem',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
    ]
