# Generated by Django 2.2.17 on 2020-11-30 11:45

from django.db import migrations


def create_new_lidertagcontaineritem(apps, schema_editor):
    SliderTagContainer = apps.get_model('customization', 'SliderTagContainer')
    try:
        container = SliderTagContainer.objects.get(key='top')
    except SliderTagContainer.DoesNotExist:
        return

    SliderTagContainerItem = apps.get_model(
        'customization', 'SliderTagContainerItem')
    SliderTagContainerItem.objects.create(
        container=container,
        tag_line='statictext_tags:render_statictext',
        args='club_privileges_block',
        position=0)


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0022_slidertagcontaineritem_enabled'),
    ]

    operations = [
        migrations.RunPython(create_new_lidertagcontaineritem, ),
    ]
