# Generated by Django 2.2.17 on 2020-11-30 14:15

from django.db import migrations


def frontpage_seo_text_alter(apps, schema_editor):
    SliderTagContainerItem = apps.get_model(
        'customization', 'SliderTagContainerItem')
    SliderTagContainerItem.objects.filter(
        args__contains='frontpage_seo_text').update(wrapper_classes='text-padding')


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0024_auto_20201130_1703'),
    ]

    operations = [
        migrations.RunPython(frontpage_seo_text_alter, ),
    ]
