# Generated by Django 2.2.19 on 2021-03-06 11:25

import colorfield.fields
from django.db import migrations, models
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0025_add_wrapper_for_frontpage_seo_text_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidertagcontaineritem',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='background color'),
        ),
        migrations.AddField(
            model_name='slidertagcontaineritem',
            name='bg_image',
            field=models.FileField(blank=True, null=True, upload_to='customization/images', validators=[stroykerbox.apps.utils.validators.validate_svg_or_image], verbose_name='background image'),
        ),
    ]
