# Generated by Django 2.2.19 on 2021-03-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0026_auto_20210306_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidertagcontainer',
            name='cache',
            field=models.BooleanField(default=False, verbose_name='cache enabled'),
        ),
        migrations.AddField(
            model_name='slidertagcontainer',
            name='cache_timeout',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='cache timeout, sec'),
        ),
    ]
