# Generated by Django 2.2.19 on 2021-03-16 12:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0028_auto_20210310_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='color_bg_fixedbtn',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='bg for float fixed buttons'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_fixedbtn',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='color for float fixed buttons'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_lk_items_bg',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='bg color for lk item box'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_lk_items_border',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='color for lk item box border'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_lk_items_hover_bg',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='bg color for lk item box on hover'),
        ),
    ]
