# Generated by Django 2.2.20 on 2021-07-17 21:48

from django.db import migrations, models


def move_frontpage_three_banner_block_to_middle_container(apps, schema_editor):
    SliderTagContainer = apps.get_model(
        'customization', 'SliderTagContainer')
    try:
        middle_container = SliderTagContainer.objects.get(key='middle')
    except SliderTagContainer.DoesNotExist:
        return

    SliderTagContainerItem = apps.get_model(
        'customization', 'SliderTagContainerItem')
    SliderTagContainerItem.objects.filter(
        container__key='top',
        tag_line='banner_tags:render_banner_set',
        args='frontpage_three_banner_block').update(container=middle_container, position=-1)


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0031_auto_20210717_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidertagcontaineritem',
            name='position',
            field=models.SmallIntegerField(default=0, verbose_name='position'),
        ),
        migrations.RunPython(
            move_frontpage_three_banner_block_to_middle_container, )
    ]
