# Generated by Django 2.2.20 on 2021-07-18 10:40

from django.db import migrations
from django.db.models import Max


def add_faq_block(apps, schema_editor):
    SliderTagContainer = apps.get_model(
        'customization', 'SliderTagContainer')

    try:
        container = SliderTagContainer.objects.get(key='middle')
    except SliderTagContainer.DoesNotExists:
        return

    SliderTagContainerItem = apps.get_model(
        'customization', 'SliderTagContainerItem')
    app_dict = {
        'container': container,
        'tag_line': 'faq_tags:render_faq_frontpage_block',
    }
    if SliderTagContainerItem.objects.filter(**app_dict).exists():
        return

    max_position = SliderTagContainerItem.objects.filter(
        container__key='middle').aggregate(Max('position'))

    app_dict['enabled'] = False
    app_dict['wrapper_classes'] = 'faq-section'
    app_dict['position'] = max_position.get('position__max', 0) + 1

    SliderTagContainerItem.objects.create(**app_dict)


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0033_auto_20210718_1326'),
    ]

    operations = [
        migrations.RunPython(add_faq_block,),
    ]
