# Generated by Django 2.2.20 on 2021-07-19 10:31

from django.db import migrations
from django.db.models import Max


def add_gift_for_phone_block(apps, schema_editor):
    SliderTagContainer = apps.get_model(
        'customization', 'SliderTagContainer')

    try:
        container = SliderTagContainer.objects.get(key='middle')
    except SliderTagContainer.DoesNotExists:
        return

    SliderTagContainerItem = apps.get_model(
        'customization', 'SliderTagContainerItem')
    app_dict = {
        'container': container,
        'tag_line': 'crm_tags:render_gift_for_phone_block',
    }
    if SliderTagContainerItem.objects.filter(**app_dict).exists():
        return

    max_position = SliderTagContainerItem.objects.filter(
        container__key='middle').aggregate(Max('position'))

    app_dict['enabled'] = False
    app_dict['position'] = max_position.get('position__max', 0) + 1

    SliderTagContainerItem.objects.create(**app_dict)


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0034_faq_block_added'),
    ]

    operations = [
        migrations.RunPython(add_gift_for_phone_block, migrations.RunPython.noop),
    ]
