# Generated by Django 2.2.20 on 2021-08-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0035_gift_for_phone_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidertagcontaineritem',
            name='bottom_indent',
            field=models.SmallIntegerField(blank=True, help_text='Bottom indent for the block (in pixels).', null=True, verbose_name='bottom indent, px'),
        ),
        migrations.AddField(
            model_name='slidertagcontaineritem',
            name='top_indent',
            field=models.SmallIntegerField(blank=True, help_text='Top indent for the block (in pixels).', null=True, verbose_name='top indent, px'),
        ),
    ]
