# Generated by Django 2.2.26 on 2022-01-13 22:34

from django.db import migrations
from django.db.models import Max


def create_multirows_banner_sets(apps, schema_editor):
    try:
        BannerMultirowSet = apps.get_model('banners', 'BannerMultirowSet')
        SliderTagContainer = apps.get_model(
            'customization', 'SliderTagContainer')
        container = SliderTagContainer.objects.get(key='middle')
    except Exception:
        return

    SliderTagContainerItem = apps.get_model(
        'customization', 'SliderTagContainerItem')
    max_position = SliderTagContainerItem.objects.filter(
        container__key='middle').aggregate(Max('position'))

    app_dict = {
        'container': container,
        'tag_line': 'banner_tags:render_multirow_banner_set',
        'enabled': False,
        'position': max_position.get('position__max', 0) + 1
    }

    key, title = 'banner-multirowset-two-col', 'Многострочные баннеры, по 2 в ряду'
    BannerMultirowSet.objects.create(key=key, title=title, banners_per_line=2)
    SliderTagContainerItem.objects.create(args=key, **app_dict)

    key, title = 'banner-multirowset-three-col', 'Многострочные баннеры, по 3 в ряду'
    BannerMultirowSet.objects.create(key=key, title=title, banners_per_line=3)
    SliderTagContainerItem.objects.create(args=key, **app_dict)


def reverse_func(apps, schema_editor):
    try:
        BannerMultirowSet = apps.get_model('banners', 'BannerMultirowSet')
        SliderTagContainerItem = apps.get_model(
            'customization', 'SliderTagContainerItem')
    except Exception:
        return

    key1, key2 = 'banner-multirowset-two-col', 'banner-multirowset-three-col'
    tag_line = 'banner_tags:render_multirow_banner_set'

    BannerMultirowSet.objects.filter(key__in=(key1, key2)).delete()
    SliderTagContainerItem.objects.filter(tag_line=tag_line).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0012_auto_20220114_0020'),
        ('customization', '0038_auto_20220107_1805'),
    ]

    operations = [
        migrations.RunPython(create_multirows_banner_sets, reverse_func),
    ]
