# Generated by Django 2.2.26 on 2022-01-13 23:19

from django.db import migrations


def del_slidersets(apps, schema_editor):
    try:
        SliderTagContainerItem = apps.get_model(
            'customization', 'SliderTagContainerItem')
    except Exception:
        return

    SliderTagContainerItem.objects.filter(
        tag_line='slide_tags:render_slide_set').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0009_auto_20220114_0204'),
        ('customization', '0039_multirow_banner_sets'),
    ]

    operations = [
        migrations.RunPython(del_slidersets, migrations.RunPython.noop),
    ]
