# Generated by Django 2.2.26 on 2022-01-14 10:23

from django.db import migrations
from django.db.models import Max

SLIDER_SET_COLS = (2, 3, 6)


def create_slider_sets(apps, schema_editor):
    try:
        SliderSet = apps.get_model('slides', 'SliderSet')
        SliderTagContainer = apps.get_model(
            'customization', 'SliderTagContainer')
        container = SliderTagContainer.objects.get(key='middle')

        SliderTagContainerItem = apps.get_model(
            'customization', 'SliderTagContainerItem')
        max_position = SliderTagContainerItem.objects.filter(
            container__key='middle').aggregate(Max('position'))
    except Exception:
        return

    app_dict = {
        'container': container,
        'tag_line': 'slide_tags:render_sliderset',
        'enabled': False,
        'position': max_position.get('position__max', 0) + 1
    }

    for i in SLIDER_SET_COLS:
        key = f'sliderset-cols-{i}'
        name = f'Набор слайдов ({i} в строке)'
        SliderSet.objects.create(
            key=key,
            cols_num=i,
            name=name
        )
        SliderTagContainerItem.objects.create(args=key, **app_dict)


def reverse_func(apps, schema_editor):
    try:
        SliderSet = apps.get_model('slides', 'SliderSet')
        SliderTagContainerItem = apps.get_model(
            'customization', 'SliderTagContainerItem')
    except Exception:
        return

    tag_line = 'slide_tags:render_sliderset'

    SliderSet.objects.filter(key__startswith='sliderset-cols-').delete()
    SliderTagContainerItem.objects.filter(tag_line=tag_line).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0010_sliderset_slidersetitem'),
        ('customization', '0040_del_sliderset_tags'),
    ]

    operations = [
        migrations.RunPython(create_slider_sets, reverse_func),
    ]
