# Generated by Django 2.2.26 on 2022-02-07 08:22

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0041_new_slider_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidertagcontaineritem',
            name='block_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='block title'),
        ),
        migrations.AddField(
            model_name='slidertagcontaineritem',
            name='title_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='title font color'),
        ),
    ]
