# Generated by Django 2.2.26 on 2022-02-07 11:18

from django.db import migrations


def create_containers(apps, schema_editor):
    SliderTagContainer = apps.get_model('customization', 'SliderTagContainer')
    SliderTagContainer.objects.create(key='staticpage_container', name='Блоки для Staticpage (контейнера)')


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0042_auto_20220207_1122'),
    ]

    operations = [
        migrations.RunPython(create_containers,)
    ]
