# Generated by Django 2.2.26 on 2022-02-17 11:14

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0043_new_tagcontainer_for_staticpages'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_callme_background',
            field=colorfield.fields.ColorField(default='#fff', help_text='--color-button-callme-background', image_field=None, max_length=18, samples=None, verbose_name='button callme background'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_callme_background_hover',
            field=colorfield.fields.ColorField(default='#E7EEF6', help_text='--color-button-callme-background-hover', image_field=None, max_length=18, samples=None, verbose_name='button callme background hover'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_callme_border',
            field=colorfield.fields.ColorField(default='#B7CBE5', help_text='--color-button-callme-border', image_field=None, max_length=18, samples=None, verbose_name='button callme border'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_callme_border_hover',
            field=colorfield.fields.ColorField(default='#1C52AC', help_text='--color-button-callme-border-hover', image_field=None, max_length=18, samples=None, verbose_name='button callme border hover'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_callme_text',
            field=colorfield.fields.ColorField(default='#2363D1', help_text='--color-button-callme-text', image_field=None, max_length=18, samples=None, verbose_name='button callme text'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_callme_text_hover',
            field=colorfield.fields.ColorField(default='#1C52AC', help_text='--color-button-callme-text-hover', image_field=None, max_length=18, samples=None, verbose_name='button callme text hover'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_cart_background',
            field=colorfield.fields.ColorField(default='#2363D1', help_text='--color-button-cart-background', image_field=None, max_length=18, samples=None, verbose_name='button cart background'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_cart_background_hover',
            field=colorfield.fields.ColorField(default='#1C52AC', help_text='--color-button-cart-background-hover', image_field=None, max_length=18, samples=None, verbose_name='button cart background hover'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_cart_border',
            field=colorfield.fields.ColorField(default='#2363D1', help_text='--color-button-cart-border', image_field=None, max_length=18, samples=None, verbose_name='button cart border'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_cart_border_hover',
            field=colorfield.fields.ColorField(default='#2363D1', help_text='--color-button-cart-border-hover', image_field=None, max_length=18, samples=None, verbose_name='button cart border hover'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_cart_text',
            field=colorfield.fields.ColorField(default='#fff', help_text='--color-button-cart-text', image_field=None, max_length=18, samples=None, verbose_name='button cart text'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_cart_text_hover',
            field=colorfield.fields.ColorField(default='#fff', help_text='--color-button-cart-text-hover', image_field=None, max_length=18, samples=None, verbose_name='button cart text hover'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_muted_background',
            field=colorfield.fields.ColorField(default='#767676', help_text='--color-button-muted-background', image_field=None, max_length=18, samples=None, verbose_name='button muted background'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_muted_background_hover',
            field=colorfield.fields.ColorField(default='#818181', help_text='--color-button-muted-background-hover', image_field=None, max_length=18, samples=None, verbose_name='button muted background hover'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_muted_border',
            field=colorfield.fields.ColorField(default='#767676', help_text='--color-button-muted-border', image_field=None, max_length=18, samples=None, verbose_name='button muted border'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_muted_border_hover',
            field=colorfield.fields.ColorField(default='#818181', help_text='--color-button-muted-border-hover', image_field=None, max_length=18, samples=None, verbose_name='button muted border hover'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_muted_text',
            field=colorfield.fields.ColorField(default='#fff', help_text='--color-button-muted-text', image_field=None, max_length=18, samples=None, verbose_name='button muted text'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_muted_text_hover',
            field=colorfield.fields.ColorField(default='#fff', help_text='--color-button-muted-text-hover', image_field=None, max_length=18, samples=None, verbose_name='button muted text hover'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_primary_background',
            field=colorfield.fields.ColorField(default='#2363D1', help_text='--color-button-primary-background', image_field=None, max_length=18, samples=None, verbose_name='button primary background'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_primary_background_hover',
            field=colorfield.fields.ColorField(default='#1C52AC', help_text='--color-button-primary-background-hover', image_field=None, max_length=18, samples=None, verbose_name='button primary background hover'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_primary_border',
            field=colorfield.fields.ColorField(default='#2363D1', help_text='--color-button-primary-border', image_field=None, max_length=18, samples=None, verbose_name='button primary border'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_primary_border_hover',
            field=colorfield.fields.ColorField(default='#2363D1', help_text='--color-button-primary-border-hover', image_field=None, max_length=18, samples=None, verbose_name='button primary border hover'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_primary_text',
            field=colorfield.fields.ColorField(default='#fff', help_text='--color-button-primary-text', image_field=None, max_length=18, samples=None, verbose_name='button primary text'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_primary_text_hover',
            field=colorfield.fields.ColorField(default='#fff', help_text='--color-button-primary-text-hover', image_field=None, max_length=18, samples=None, verbose_name='button primary text hover'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_secondary_background',
            field=colorfield.fields.ColorField(default='#fff', help_text='--color-button-secondary-background', image_field=None, max_length=18, samples=None, verbose_name='button secondary background'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_secondary_background_hover',
            field=colorfield.fields.ColorField(default='#E7EEF6', help_text='--color-button-secondary-background-hover', image_field=None, max_length=18, samples=None, verbose_name='button secondary background hover'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_secondary_border',
            field=colorfield.fields.ColorField(default='#B7CBE5', help_text='--color-button-secondary-border', image_field=None, max_length=18, samples=None, verbose_name='button secondary border'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_secondary_border_hover',
            field=colorfield.fields.ColorField(default='#1C52AC', help_text='--color-button-secondary-border-hover', image_field=None, max_length=18, samples=None, verbose_name='button secondary border hover'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_secondary_text',
            field=colorfield.fields.ColorField(default='#2363D1', help_text='--color-button-secondary-text', image_field=None, max_length=18, samples=None, verbose_name='button secondary text'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_button_secondary_text_hover',
            field=colorfield.fields.ColorField(default='#1C52AC', help_text='--color-button-secondary-text-hover', image_field=None, max_length=18, samples=None, verbose_name='button secondary text hover'),
        ),
        migrations.AlterField(
            model_name='slidertagcontaineritem',
            name='tag_line',
            field=models.CharField(choices=[('users_tags:render_user_lk_link', 'users_tags:render_user_lk_link'), ('catalog_tags:render_catalog_categories_menu', 'catalog_tags:render_catalog_categories_menu'), ('catalog_tags:render_catalog_categories_menu_mobile', 'catalog_tags:render_catalog_categories_menu_mobile'), ('catalog_tags:render_catalog_categories_menu_simple', 'catalog_tags:render_catalog_categories_menu_simple'), ('catalog_tags:render_product_availability_status', 'catalog_tags:render_product_availability_status'), ('catalog_tags:render_product_availability_status_text', 'catalog_tags:render_product_availability_status_text'), ('catalog_tags:render_cart_related_products', 'catalog_tags:render_cart_related_products'), ('catalog_tags:render_catalog_product_teaser', 'catalog_tags:render_catalog_product_teaser'), ('catalog_tags:render_bestsellers_slider', 'catalog_tags:render_bestsellers_slider'), ('catalog_tags:render_sales_slider', 'catalog_tags:render_sales_slider'), ('catalog_tags:render_product_images_slider', 'catalog_tags:render_product_images_slider'), ('catalog_tags:render_product_flags', 'catalog_tags:render_product_flags'), ('catalog_tags:render_product_flags_v2', 'catalog_tags:render_product_flags_v2'), ('catalog_tags:render_product_price_chart', 'catalog_tags:render_product_price_chart'), ('catalog_tags:render_product_documents', 'catalog_tags:render_product_documents'), ('catalog_tags:render_products_list_header', 'catalog_tags:render_products_list_header'), ('catalog_tags:render_catalog_filter', 'catalog_tags:render_catalog_filter'), ('catalog_tags:render_product_properties', 'catalog_tags:render_product_properties'), ('catalog_tags:render_found_cheaper_panel', 'catalog_tags:render_found_cheaper_panel'), ('catalog_tags:render_product_set_slider', 'catalog_tags:render_product_set_slider'), ('catalog_tags:render_related_products', 'catalog_tags:render_related_products'), ('catalog_tags:render_catalog_categories_list_popular', 'catalog_tags:render_catalog_categories_list_popular'), ('catalog_tags:render_root_category_slider', 'catalog_tags:render_root_category_slider'), ('catalog_tags:render_root_category_top_products', 'catalog_tags:render_root_category_top_products'), ('catalog_tags:render_category_image', 'catalog_tags:render_category_image'), ('catalog_tags:render_category_maybeinterested_block', 'catalog_tags:render_category_maybeinterested_block'), ('catalog_tags:render_product_teaser', 'catalog_tags:render_product_teaser'), ('catalog_tags:render_product_list_slider', 'catalog_tags:render_product_list_slider'), ('commerce_tags:render_cart', 'commerce_tags:render_cart'), ('commerce_tags:render_commerce_login_form', 'commerce_tags:render_commerce_login_form'), ('utils_tags:render_footer_social_links', 'utils_tags:render_footer_social_links'), ('utils_tags:render_header_contact_phone', 'utils_tags:render_header_contact_phone'), ('utils_tags:render_yandex_metrika_goal', 'utils_tags:render_yandex_metrika_goal'), ('statictext_tags:render_statictext_var', 'statictext_tags:render_statictext_var'), ('statictext_tags:render_statictext', 'statictext_tags:render_statictext'), ('news_tags:render_news_teaser', 'news_tags:render_news_teaser'), ('news_tags:render_news_slider', 'news_tags:render_news_slider'), ('news_tags:render_related_news', 'news_tags:render_related_news'), ('menu_tags:render_menu', 'menu_tags:render_menu'), ('menu_tags:render_custom_navigation', 'menu_tags:render_custom_navigation'), ('crm_tags:render_feedback_message_request_form', 'crm_tags:render_feedback_message_request_form'), ('crm_tags:render_callme_request_form', 'crm_tags:render_callme_request_form'), ('crm_tags:render_gift_for_phone_block', 'crm_tags:render_gift_for_phone_block'), ('article_tags:render_articles_slider', 'article_tags:render_articles_slider'), ('article_tags:render_related_articles', 'article_tags:render_related_articles'), ('article_tags:render_article_related_products', 'article_tags:render_article_related_products'), ('article_tags:render_other_articles_slider', 'article_tags:render_other_articles_slider'), ('slide_tags:render_big_slides', 'slide_tags:render_big_slides'), ('slide_tags:render_partner_slides', 'slide_tags:render_partner_slides'), ('slide_tags:render_sliderset', 'slide_tags:render_sliderset'), ('banner_tags:render_catalog_page_banners_horizontal', 'banner_tags:render_catalog_page_banners_horizontal'), ('banner_tags:render_catalog_page_sidebar_banners', 'banner_tags:render_catalog_page_sidebar_banners'), ('banner_tags:render_sidebar_banners', 'banner_tags:render_sidebar_banners'), ('banner_tags:render_banners', 'banner_tags:render_banners'), ('banner_tags:render_banners_horizontal', 'banner_tags:render_banners_horizontal'), ('banner_tags:render_banner_set', 'banner_tags:render_banner_set'), ('banner_tags:render_multirow_banner_set', 'banner_tags:render_multirow_banner_set'), ('seo_tags:render_meta_tags', 'seo_tags:render_meta_tags'), ('seo_tags:render_breadcrumbs', 'seo_tags:render_breadcrumbs'), ('seo_tags:render_h1', 'seo_tags:render_h1'), ('seo_tags:render_title', 'seo_tags:render_title'), ('location_tags:render_current_location_block', 'location_tags:render_current_location_block'), ('address_tags:render_frontpage_partner_promo_block', 'address_tags:render_frontpage_partner_promo_block'), ('address_tags:render_partners_yamap', 'address_tags:render_partners_yamap'), ('reviews_tags:render_review_form', 'reviews_tags:render_review_form'), ('reviews_tags:render_product_reviews', 'reviews_tags:render_product_reviews'), ('reviews_tags:render_rating_five_stars', 'reviews_tags:render_rating_five_stars'), ('reviews_tags:render_product_average_rating', 'reviews_tags:render_product_average_rating'), ('subscription_tags:render_footer_subscription_form', 'subscription_tags:render_footer_subscription_form'), ('customization_tags:render_tag_container', 'customization_tags:render_tag_container'), ('faq_tags:render_faq_frontpage_block', 'faq_tags:render_faq_frontpage_block')], help_text='The name of the tag. Which should be called in a template.', max_length=60, verbose_name='tag function name'),
        ),
    ]
