# Generated by Django 2.2.26 on 2022-05-06 13:44

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0045_auto_20220506_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='feedback_form_border',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='--feedback-form-border', image_field=None, max_length=18, null=True, samples=None, verbose_name='feedback form: border color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='feedback_form_input_border',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='--feedback-form-input-border', image_field=None, max_length=18, null=True, samples=None, verbose_name='feedback form: input border color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='feedback_form_text',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='--feedback-form-text', image_field=None, max_length=18, null=True, samples=None, verbose_name='feedback form: text color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='feedback_form_title',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='--feedback-form-title', image_field=None, max_length=18, null=True, samples=None, verbose_name='feedback form: title color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='search_field_btn_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='search field button color'),
        ),
    ]
