# Generated by Django 3.2.13 on 2022-05-13 08:19

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0046_auto_20220506_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='catalog_menu_button_bg',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='--catalog-menu-button-bg ', image_field=None, max_length=18, null=True, samples=None, verbose_name='catalog menu button background'),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='feedback_form_section_bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='--feedback-form-section-bg-color', image_field=None, max_length=18, null=True, samples=None, verbose_name='bg color for section block with feedback form'),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='search_field_bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='--search-field-bg-color ', image_field=None, max_length=18, null=True, samples=None, verbose_name='search field bg color'),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='search_field_border_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='--search-field-border-color ', image_field=None, max_length=18, null=True, samples=None, verbose_name='search field border color'),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='search_field_btn_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='--search-field-btn-color ', image_field=None, max_length=18, null=True, samples=None, verbose_name='search field button color'),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='search_field_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='--search-field-font-color ', image_field=None, max_length=18, null=True, samples=None, verbose_name='search field font color'),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='search_field_placeholder_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='--search-field-placeholder-font-color ', image_field=None, max_length=18, null=True, samples=None, verbose_name='search field placeholder font color'),
        ),
        migrations.AlterField(
            model_name='customfont',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slidertagcontaineritem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slidertagcontaineritem',
            name='tag_line',
            field=models.CharField(choices=[], help_text='The name of the tag. Which should be called in a template.', max_length=60, verbose_name='tag function name'),
        ),
    ]
