# Generated by Django 3.2.13 on 2022-05-31 19:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0048_auto_20220531_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='catalog_menu_link_hover',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='--catalog-menu-link-hover', image_field=None, max_length=18, null=True, samples=None, verbose_name='catalog menu link color on hover'),
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='catalog_menu_button_bg',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='--catalog-menu-button-bg', image_field=None, max_length=18, null=True, samples=None, verbose_name='catalog menu button background'),
        ),
    ]
