# Generated by Django 3.2.13 on 2022-06-09 09:55

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0049_auto_20220531_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='color_card_border',
            field=colorfield.fields.ColorField(default='#D9D9DE', help_text='--color-card-border', image_field=None, max_length=18, samples=None, verbose_name='product teaser border color'),
        ),
    ]
