# Generated by Django 3.2.13 on 2022-06-28 18:24

from django.db import migrations


def create_new_block(apps, schema_editor):
    SliderTagContainer = apps.get_model('customization', 'SliderTagContainer')
    try:
        container = SliderTagContainer.objects.get(key='middle')
    except SliderTagContainer.DoesNotExist:
        return

    SliderTagContainerItem = apps.get_model(
        'customization', 'SliderTagContainerItem')
    SliderTagContainerItem.objects.create(
        container=container,
        tag_line='catalog_tags:render_root_category_slider',
        enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0050_colorscheme_color_card_border'),
    ]

    operations = [
        migrations.RunPython(create_new_block, ),
    ]
