# Generated by Django 3.2.13 on 2022-07-20 11:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0051_root_category_block_for_frontpage_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='feedback_form_bg',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='--feedback-form-bg', image_field=None, max_length=18, null=True, samples=None, verbose_name='bg color for feedback form'),
        ),
    ]
