# Generated by Django 3.2.13 on 2022-09-08 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0052_colorscheme_feedback_form_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inline_styles', models.TextField(blank=True, null=True, verbose_name='inline styles')),
                ('file', models.FileField(blank=True, null=True, upload_to='customization/custom_styles', validators=[django.core.validators.FileExtensionValidator(('css',))], verbose_name='custom css file')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('position', models.SmallIntegerField(default=0, verbose_name='position')),
            ],
            options={
                'verbose_name': 'custom css styles',
                'verbose_name_plural': 'custom css styles',
                'ordering': ['position'],
            },
        ),
    ]
