# Generated by Django 3.2.13 on 2022-09-16 13:32

from django.db import migrations

from stroykerbox.apps.customization import DEFAULT_TAG_CONTAINERS


def update_containers(apps, schema_editor):
    SliderTagContainer = apps.get_model('customization', 'SliderTagContainer')
    for key, name in DEFAULT_TAG_CONTAINERS.items():
        SliderTagContainer.objects.filter(key=key).update(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0053_customstyle'),
    ]

    operations = [
        migrations.RunPython(update_containers,)
    ]
