# Generated by Django 3.2.15 on 2022-09-19 20:31

from django.db import migrations, models

from stroykerbox.apps.customization import DEFAULT_TAG_CONTAINERS


def create_containers(apps, schema_editor):
    SliderTagContainer = apps.get_model('customization', 'SliderTagContainer')
    for key, name in DEFAULT_TAG_CONTAINERS.items():
        SliderTagContainer.objects.get_or_create(key=key, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0054_renaming_for_tag_containers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTemplateBlock',
            fields=[
                ('key', models.SlugField(max_length=70, primary_key=True, serialize=False, verbose_name='key')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('code', models.TextField(verbose_name='template code')),
            ],
            options={
                'verbose_name': 'custom template block',
                'verbose_name_plural': 'custom template blocks',
            },
        ),
        migrations.RunPython(create_containers, migrations.RunPython.noop)
    ]
