# Generated by Django 3.2.15 on 2022-09-22 15:21

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0055_auto_20220919_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorscheme',
            name='category_menu_font_highlight_color',
            field=colorfield.fields.ColorField(default='#ff5f00', help_text='Цвет шрифта при "выделении шрифтом" пункта в выпадающем меню категорий каталога.', image_field=None, max_length=18, samples=None, verbose_name='category menu font highlight color'),
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='category_menu_underline_highlight_color',
            field=colorfield.fields.ColorField(default='#ff5f00', help_text='Цвет подчеркивания при "выделении подчеркиванием" пункта в выпадающем меню категорий каталога.', image_field=None, max_length=18, samples=None, verbose_name='category menu underline highlight color'),
        ),
    ]
