# Generated by Django 3.2.15 on 2022-10-10 14:57

from django.db import migrations, models
from django.db.models import Max


def move_feedback_form_to_bottom_container(apps, schema_editor):
    SliderTagContainer = apps.get_model('customization', 'SliderTagContainer')
    try:
        bottom_container = SliderTagContainer.objects.get(key='bottom')
    except SliderTagContainer.DoesNotExist:
        return

    SliderTagContainerItem = apps.get_model(
        'customization', 'SliderTagContainerItem')
    SliderTagContainerItem.objects.filter(
        enabled=True, container=bottom_container).update(frontpage_only=True)

    max_position = SliderTagContainerItem.objects.filter(
        container__key='middle').aggregate(Max('position'))

    params = {
        'without_wrapper': True,
        'enabled': True,
        'position': max_position.get('position__max', 0) + 1,
        'frontpage_only': False
    }

    SliderTagContainerItem.objects.update_or_create(
        container=bottom_container,
        tag_line='crm_tags:render_feedback_form_section',
        defaults=params
    )


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0056_auto_20220922_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidertagcontaineritem',
            name='frontpage_only',
            field=models.BooleanField(
                default=False, verbose_name='frontpage only'),
        ),
        migrations.RunPython(
            move_feedback_form_to_bottom_container, migrations.RunPython.noop),
    ]
