# Generated by Django 3.2.15 on 2022-11-28 10:18

from django.db import migrations
from django.db.models import Min

TAG_LINE_KEY = 'slide_tags:render_big_banners'


def create_new_block(apps, schema_editor):
    SliderTagContainer = apps.get_model('customization', 'SliderTagContainer')
    try:
        container = SliderTagContainer.objects.get(key='middle')
    except SliderTagContainer.DoesNotExist:
        return

    SliderTagContainerItem = apps.get_model(
        'customization', 'SliderTagContainerItem')

    min_position = SliderTagContainerItem.objects.filter(
        container__key='middle').aggregate(Min('position'))

    position = (min_position.get('position__min', 0) or 0) - 1

    SliderTagContainerItem.objects.create(
        container=container,
        tag_line=TAG_LINE_KEY,
        enabled=False,
        position=position,
        frontpage_only=True)


def reverse_func(apps, schema_editor):
    try:
        SliderTagContainerItem = apps.get_model(
            'customization', 'SliderTagContainerItem')
    except Exception:
        return

    SliderTagContainerItem.objects.filter(tag_line=TAG_LINE_KEY).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0057_auto_20221010_1757'),
    ]

    operations = [
        migrations.RunPython(create_new_block, reverse_func),
    ]
