# Generated by Django 3.2.20 on 2023-09-13 12:15

from django.db import migrations

KEY = 'pre_header'


def create_new_container(apps, schema_editor):
    SliderTagContainer = apps.get_model('customization', 'SliderTagContainer')
    if not SliderTagContainer.objects.filter(key=KEY).exists():
        SliderTagContainer.objects.create(
            key=KEY, name='Блоки для области над Шапкой.')


def del_new_container(apps, schema_editor):
    SliderTagContainer = apps.get_model('customization', 'SliderTagContainer')
    SliderTagContainer.objects.filter(key=KEY).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0059_auto_20221221_2054'),
    ]

    operations = [
        migrations.RunPython(create_new_container, del_new_container)
    ]
