# Generated by Django 3.2.20 on 2023-10-06 14:17

from django.db import migrations


KEY = 'post_header'


def create_new_container(apps, schema_editor):
    SliderTagContainer = apps.get_model('customization', 'SliderTagContainer')
    if not SliderTagContainer.objects.filter(key=KEY).exists():
        SliderTagContainer.objects.create(
            key=KEY, name='Блоки для области под Шапкой.')

    # удаляем ненужные "вшитые" контейнеры
    # https://redmine.fancymedia.ru/issues/8861#note-21
    SliderTagContainer.objects.filter(key__in=('top_extra', 'top')).delete()


def del_new_container(apps, schema_editor):
    SliderTagContainer = apps.get_model('customization', 'SliderTagContainer')
    SliderTagContainer.objects.filter(key=KEY).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0060_pre_header_tagcontainer'),
    ]

    operations = [
        migrations.RunPython(create_new_container, del_new_container)
    ]
