# Generated by Django 3.2.20 on 2024-01-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0063_auto_20231228_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilemenubutton',
            name='type_additional_menu',
        ),
    ]
