# Generated by Django 3.2.25 on 2024-12-18 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=128, verbose_name='поисковый запрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата/время запроса')),
                ('meta_data', models.JSONField(default=dict, verbose_name='meta-данные запроса')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'поисковый запрос',
                'verbose_name_plural': 'поисковые запросы',
                'ordering': ('-created_at',),
            },
        ),
    ]
