# Generated by Django 3.2.25 on 2025-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchWordAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_word', models.CharField(help_text='Слово, введенное в поисковую строку.', max_length=32, verbose_name='слово')),
                ('alias', models.CharField(help_text='Алиас поискового слова.', max_length=32, verbose_name='алиас')),
            ],
            options={
                'verbose_name': 'поисковый алияс',
                'verbose_name_plural': 'поисковые алиясы',
            },
        ),
    ]
