# Generated by Django 3.2.25 on 2024-12-24

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='portfolio/images', verbose_name='фото для тизера')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='позиция')),
                ('published', models.BooleanField(default=True, verbose_name='отображать на сайте')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'портфолио',
                'verbose_name_plural': 'портфолио',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='позиция')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'категория портфолио',
                'verbose_name_plural': 'категории портфолио',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='portfolio/images', verbose_name='фото')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='позиция')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'фото портфолио',
                'verbose_name_plural': 'фотографии портфолио',
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.portfoliocategory', verbose_name='категория'),
        ),
    ]
