# Generated by Django 2.2.8 on 2019-12-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotsTxt',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.Site')),
                ('content', models.TextField(blank=True, default='', verbose_name='robots.txt file content')),
            ],
        ),
    ]
