# Generated by Django 2.2.8 on 2019-12-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='always use full page path with trailing slash: "/news/", "/"', max_length=255, unique=True, verbose_name='url')),
                ('title', models.CharField(blank=True, default='', help_text='Override &lt;title tag', max_length=255, verbose_name='title')),
                ('h1', models.TextField(blank=True, default='', help_text='Override &lt;h1&gt; tag contents', max_length=255, verbose_name='h1')),
                ('meta_keywords', models.TextField(blank=True, default='', verbose_name='meta keywords')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='meta description')),
            ],
            options={
                'verbose_name': 'meta tag',
                'verbose_name_plural': 'meta tags',
            },
        ),
        migrations.AlterModelOptions(
            name='robotstxt',
            options={'verbose_name': 'robots.txt file', 'verbose_name_plural': 'robots.txt files'},
        ),
    ]
