# Generated by Django 3.2.15 on 2023-01-20 11:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_auto_20191220_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatag',
            name='seo_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Formatted and optimized text to attract the attention of search engines.', null=True, verbose_name='seo text'),
        ),
        migrations.AlterField(
            model_name='metatag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
