# Generated by Django 2.2.7 on 2019-11-13 16:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('key', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='menu key')),
                ('title', models.CharField(max_length=255, verbose_name='menu title')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor', models.CharField(max_length=50, verbose_name='anchor')),
                ('title', models.CharField(max_length=50, verbose_name='link title attribute')),
                ('url', models.CharField(help_text='Relative path: /news/ or /', max_length=255, validators=[django.core.validators.RegexValidator('^/([a-z0-9-_A-Z]+/#?)*$', message='Must start and end with slash')], verbose_name='url')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('published', models.BooleanField(default=True, verbose_name='hide or show item')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.Menu', verbose_name='menu')),
                ('parent', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='menu.MenuItem', verbose_name='parent menu item')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
                'ordering': ('position',),
            },
        ),
    ]
