# Generated by Django 2.2.9 on 2020-02-12 13:39

from django.db import migrations

def create_header_menu(apps, schema_editor):
    Statictext = apps.get_model('menu', 'Menu')
    Statictext.objects.create(key='header_menu',
                              title='Menu for website header'
                              )

class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_header_menu, ),
    ]
