# Generated by Django 2.2.9 on 2020-02-12 13:53

from django.db import migrations


def create_header_mobile_menu(apps, schema_editor):
    Menu = apps.get_model('menu', 'Menu')
    Menu.objects.create(key='header_mobile_menu',
                              title='Menu for website header in mobile mode'
                              )
class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_header_menu'),
    ]

    operations = [
        migrations.RunPython(create_header_mobile_menu, ),
    ]
