# Generated by Django 2.2.9 on 2020-03-05 13:46

from django.db import migrations


def create_menu(apps, schema_editor):
    Menu = apps.get_model('menu', 'Menu')
    Menu.objects.create(key='article_sidebar_menu',
                              title='Menu for the sidebar on the article page displayed in a wide view'
                              )

class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_header_mobile_menu'),
    ]

    operations = [
        migrations.RunPython(create_menu, ),
    ]
