# Generated by Django 2.2.11 on 2020-03-11 19:36

from django.db import migrations

def create_menu(apps, schema_editor):
    Menu = apps.get_model('menu', 'Menu')
    Menu.objects.create(key='footer_customer_menu',
                              title='Menu with information for customers (for footer).'
                              )

class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_article_sidebar_menu'),
    ]

    operations = [
        migrations.RunPython(create_menu, ),
    ]
