# Generated by Django 2.2.12 on 2020-10-08 14:12

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_footer_customer_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNavigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='This value is used in the code, do not touch it!', max_length=32, verbose_name='key')),
                ('title', models.CharField(max_length=70, verbose_name='name')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'custom navigation',
                'verbose_name_plural': 'custom navigations',
            },
        ),
        migrations.AlterField(
            model_name='menu',
            name='key',
            field=models.CharField(help_text='Key is used in the code, do not modify it', max_length=60, primary_key=True, serialize=False, verbose_name='menu key'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='menu.MenuItem', verbose_name='parent menu item'),
        ),
        migrations.CreateModel(
            name='CustomLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='name')),
                ('url', models.CharField(db_index=True, help_text='Example: "/about/" or "/"', max_length=255, verbose_name='url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='navigation/images', verbose_name='image')),
                ('svg', models.FileField(blank=True, null=True, upload_to='navigation/images', validators=[stroykerbox.apps.utils.validators.validator_svg], verbose_name='svg image')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('navigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='menu.CustomNavigation')),
            ],
            options={
                'verbose_name': 'navigation link',
                'verbose_name_plural': 'navigation links',
                'ordering': ['position'],
            },
        ),
    ]
