# Generated by Django 2.2.12 on 2020-10-08 14:23

from django.db import migrations


def create_frontpage_top_nav(app, schema):
    CustomNavigation = app.get_model('menu', 'CustomNavigation')
    CustomNavigation.objects.create(
        key='frontpage_top_pages_nav',
        title='ТОПовые страницы',
        comment='Набор для блока кастомных ссылок на главной.'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20201008_1712'),
    ]

    operations = [
        migrations.RunPython(create_frontpage_top_nav, ),
    ]
