# Generated by Django 2.2.20 on 2021-08-16 11:45

import colorfield.fields
from django.db import migrations, models
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_frontpage_top_custom_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='customnavigation',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='background color'),
        ),
        migrations.AddField(
            model_name='customnavigation',
            name='bg_image',
            field=models.FileField(blank=True, null=True, upload_to='menu/images', validators=[stroykerbox.apps.utils.validators.validate_svg_or_image], verbose_name='background image'),
        ),
        migrations.AddField(
            model_name='customnavigation',
            name='bottom_indent',
            field=models.SmallIntegerField(blank=True, help_text='Bottom indent for the block (in pixels).', null=True, verbose_name='bottom indent, px'),
        ),
        migrations.AddField(
            model_name='customnavigation',
            name='published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
        migrations.AddField(
            model_name='customnavigation',
            name='top_indent',
            field=models.SmallIntegerField(blank=True, help_text='Top indent for the block (in pixels).', null=True, verbose_name='top indent, px'),
        ),
    ]
