# Generated by Django 3.2.15 on 2023-01-30 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20220923_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='download',
            field=models.BooleanField(default=False, verbose_name='download link'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(help_text='Relative path: /news/ or /', max_length=255, validators=[django.core.validators.RegexValidator('^/.*$', message='Must start with slash')], verbose_name='url'),
        ),
    ]
