# Generated by Django 3.2.15 on 2023-03-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20230130_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='css_class',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='css class'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(max_length=255, verbose_name='url'),
        ),
    ]
