# Generated by Django 3.2.15 on 2023-04-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20230329_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='new_tab',
            field=models.BooleanField(default=False, verbose_name='open in new tab'),
        ),
    ]
