# Generated by Django 3.2.25 on 2024-12-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='B24Log',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'lead_id',
                    models.PositiveIntegerField(verbose_name='id на стороне b24'),
                ),
                ('object_id', models.PositiveIntegerField()),
                (
                    'data',
                    models.JSONField(default=dict, verbose_name='данные ответа от b24'),
                ),
                (
                    'content_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.contenttype',
                    ),
                ),
            ],
            options={
                'verbose_name': 'запрос на создание объекта B24',
                'verbose_name_plural': 'запросы на создание объектов B24',
                'ordering': ('-lead_id',),
            },
        ),
    ]
