# Generated by Django 2.2.6 on 2019-10-07 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_auto_20191007_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Sum of all the products personal prices and their quantities.', max_digits=8, null=True, verbose_name='sum of all the products prices')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Final price of the order to be paid by a customer including a delivery cost.', max_digits=8, null=True, verbose_name='final price of the order')),
                ('is_paid', models.BooleanField(db_index=True, default=False, verbose_name='order is paid')),
                ('status', models.CharField(choices=[('draft', 'Draft order'), ('new', 'New order'), ('processed', 'Processed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('status_changed_at', models.DateTimeField(db_index=True, null=True, verbose_name='status changed at')),
                ('comment', models.TextField(blank=True, default='', verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderProductMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.DecimalField(decimal_places=0, help_text='Product price at the moment of purchase', max_digits=6, verbose_name='product price')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='commerce.OrderProductMembership', to='catalog.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderCancelled',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commerce.order',),
        ),
        migrations.CreateModel(
            name='OrderCompleted',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commerce.order',),
        ),
        migrations.CreateModel(
            name='OrderInProgress',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commerce.order',),
        ),
        migrations.CreateModel(
            name='OrderNew',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commerce.order',),
        ),
        migrations.CreateModel(
            name='OrderProcessed',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commerce.order',),
        ),
    ]
