# Generated by Django 2.2.6 on 2019-10-11 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='name')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('geo_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='latitude of the stock location', max_digits=9, null=True, verbose_name='latitude')),
                ('geo_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='longitude of the stock location', max_digits=9, null=True, verbose_name='longitude')),
            ],
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commerce.Address')),
            ],
            options={
                'verbose_name': 'pickup point',
                'verbose_name_plural': 'pickup points',
            },
            bases=('commerce.address',),
        ),
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commerce.Address')),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='delivery price')),
            ],
            options={
                'verbose_name': 'transport company',
                'verbose_name_plural': 'transport companies',
            },
            bases=('commerce.address',),
        ),
    ]
