# Generated by Django 2.2.6 on 2019-10-19 10:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('commerce', '0002_address_pickuppoint_transportcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToAddressDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^7[\\d]{10}$', 'Enter a valid phone number starting with "7" followed by 10 digits.', 'invalid')], verbose_name='phone')),
            ],
            options={
                'ordering': ('-pk',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToTCDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^7[\\d]{10}$', 'Enter a valid phone number starting with "7" followed by 10 digits.', 'invalid')], verbose_name='phone')),
            ],
            options={
                'ordering': ('-pk',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['pickupdelivery', 'toaddressdelivery', 'totcdelivery']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='PickUpDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^7[\\d]{10}$', 'Enter a valid phone number starting with "7" followed by 10 digits.', 'invalid')], verbose_name='phone')),
                ('point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.PickupPoint')),
            ],
            options={
                'verbose_name': 'pick up delivery',
                'verbose_name_plural': 'pick up deliveries',
            },
        ),
    ]
