# Generated by Django 2.2.6 on 2019-10-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_auto_20191019_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='car model')),
                ('carrying', models.PositiveSmallIntegerField(verbose_name='carrying, kg')),
                ('volume', models.FloatField(verbose_name='volume, m3')),
                ('length', models.FloatField(default=0, verbose_name='length, m')),
                ('height', models.FloatField(default=0, verbose_name='height, m')),
                ('width', models.FloatField(default=0, verbose_name='width, m')),
                ('store_start_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, max_length=12, verbose_name='cost of start from store, rub')),
                ('cost_km', models.DecimalField(decimal_places=2, default=0, max_digits=10, max_length=12, verbose_name='cost of km, rub')),
            ],
            options={
                'verbose_name': 'delivery car',
                'verbose_name_plural': 'delivery cars',
            },
        ),
    ]
