# Generated by Django 2.2.6 on 2019-10-22 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_short_description'),
        ('commerce', '0004_deliverycar'),
    ]

    operations = [
        migrations.AddField(
            model_name='toaddressdelivery',
            name='address',
            field=models.CharField(default='', max_length=256, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toaddressdelivery',
            name='address_latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=13, null=True, verbose_name='address latitude'),
        ),
        migrations.AddField(
            model_name='toaddressdelivery',
            name='address_longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=13, null=True, verbose_name='address longitude'),
        ),
        migrations.AddField(
            model_name='toaddressdelivery',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Stock'),
        ),
    ]
