# Generated by Django 2.2.6 on 2019-10-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_auto_20191022_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='toaddressdelivery',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.DeliveryCar'),
        ),
        migrations.AddField(
            model_name='totcdelivery',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commerce.TransportCompany'),
            preserve_default=False,
        ),
    ]
