# Generated by Django 2.2.6 on 2019-10-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_auto_20191022_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='toaddressdelivery',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, max_length=12, verbose_name='cost of delivery, rub'),
        ),
        migrations.AddField(
            model_name='toaddressdelivery',
            name='distance_km',
            field=models.PositiveIntegerField(null=True, verbose_name='distance, km'),
        ),
    ]
