# Generated by Django 2.2.6 on 2019-10-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_auto_20191023_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
