# Generated by Django 2.2.6 on 2019-11-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_order_payment_method_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductmembership',
            name='weight',
            field=models.FloatField(default=0, verbose_name='product weight sum, kg'),
        ),
        migrations.AlterField(
            model_name='orderproductmembership',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='product quantity sum'),
        ),
    ]
