# Generated by Django 2.2.6 on 2019-11-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_auto_20191101_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupdelivery',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, max_length=12, verbose_name='cost of delivery, rub'),
        ),
        migrations.AddField(
            model_name='totcdelivery',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, max_length=12, verbose_name='cost of delivery, rub'),
        ),
    ]
