# Generated by Django 2.2.6 on 2019-11-06 07:44

from django.db import migrations, models


def rename_payment_method_field(apps, schema_editor):
    Order = apps.get_model('commerce', 'Order')
    Order.objects.all().update(payment_method=models.F('payment_method_id'))


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_auto_20191102_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Invoicing'), (1, 'Card upon receipt'), (2, 'Cash upon receipt'), (3, 'On-line'), (4, 'Credit')], null=True, verbose_name='payment method'),
        ),
        migrations.RunPython(rename_payment_method_field, ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method_id',
        ),
    ]
