# Generated by Django 2.2.6 on 2019-11-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_auto_20191106_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickupdelivery',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='toaddressdelivery',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='totcdelivery',
            old_name='first_name',
            new_name='name',
        ),
    ]
