# Generated by Django 2.2.7 on 2019-11-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_auto_20191106_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupdelivery',
            name='email',
            field=models.EmailField(default='', max_length=60, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toaddressdelivery',
            name='email',
            field=models.EmailField(default='', max_length=60, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totcdelivery',
            name='email',
            field=models.EmailField(default='testmail@localhost.local', max_length=60, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pickupdelivery',
            name='name',
            field=models.CharField(max_length=30, verbose_name='contact person'),
        ),
        migrations.AlterField(
            model_name='toaddressdelivery',
            name='name',
            field=models.CharField(max_length=30, verbose_name='contact person'),
        ),
        migrations.AlterField(
            model_name='totcdelivery',
            name='name',
            field=models.CharField(max_length=30, verbose_name='contact person'),
        ),
    ]
