# Generated by Django 2.2.7 on 2019-11-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_auto_20191107_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='from_cart',
            field=models.BooleanField(default=False, help_text='Created from the cart content, not manually by a manager.', verbose_name='created from cart'),
        ),
    ]
