# Generated by Django 2.2.7 on 2019-11-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_order_from_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductmembership',
            name='personal_product_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Personal product price at the moment of purchase', max_digits=8, verbose_name='personal product price'),
            preserve_default=False,
        ),
    ]
