# Generated by Django 2.2.7 on 2019-11-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_orderproductmembership_personal_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoicing_with_vat',
            field=models.BooleanField(default=True, verbose_name='invoicing with VAT'),
        ),
    ]
