# Generated by Django 2.2.9 on 2020-01-06 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20191227_1108'),
        ('commerce', '0016_order_invoicing_with_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='address',
            name='geo_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='latitude of the location', max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='address',
            name='geo_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='longitude of the location', max_digits=9, null=True, verbose_name='longitude'),
        ),
    ]
