# Generated by Django 2.2.9 on 2020-01-08 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20191227_1108'),
        ('commerce', '0017_auto_20200106_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycar',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
