# Generated by Django 2.2.11 on 2020-03-31 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_deliverycar_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toaddressdelivery',
            options={'verbose_name': 'delivery to address', 'verbose_name_plural': 'delivery to addresses'},
        ),
        migrations.AlterModelOptions(
            name='totcdelivery',
            options={'verbose_name': 'delivery to tc', 'verbose_name_plural': 'delivery to tc'},
        ),
        migrations.AddField(
            model_name='order',
            name='closing_document',
            field=models.FileField(blank=True, null=True, upload_to='order/documents', verbose_name='Closing document'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False, verbose_name='order is shipped'),
        ),
        migrations.AlterField(
            model_name='orderproductmembership',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='commerce.Order'),
        ),
    ]
