# Generated by Django 2.2.12 on 2020-10-13 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_auto_20200331_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Comment on the order.', verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag of the payment status of the order.', verbose_name='order is paid'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False, help_text='Flag of the shipping status of the order to the customer.', verbose_name='order is shipped'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft order'), ('new', 'New order'), ('processed', 'Processed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', help_text='Global order status.', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='pickupdelivery',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[78][\\d]{10}$', 'Enter a valid phone number starting with "7 (or 8)" followed by 10 digits.', 'invalid')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='toaddressdelivery',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[78][\\d]{10}$', 'Enter a valid phone number starting with "7 (or 8)" followed by 10 digits.', 'invalid')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='totcdelivery',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[78][\\d]{10}$', 'Enter a valid phone number starting with "7 (or 8)" followed by 10 digits.', 'invalid')], verbose_name='phone'),
        ),
    ]
