# Generated by Django 2.2.19 on 2021-03-10 14:15

from django.db import migrations, models
import django.db.models.deletion


def reset_delivery_points(apps, schema_editor):
    PickUpDelivery = apps.get_model('commerce', 'PickUpDelivery')
    PickUpDelivery.objects.filter(point__isnull=False).update(point=None)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('commerce', '0020_auto_20201013_1957'),
    ]

    operations = [
        migrations.RunPython(reset_delivery_points, ),
        migrations.AlterField(
            model_name='pickupdelivery',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Stock'),
        ),
        migrations.DeleteModel(
            name='PickupPoint',
        ),
    ]
