# Generated by Django 2.2.19 on 2021-04-08 19:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_auto_20210310_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderContactData',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 primary_key=True, serialize=False, to='commerce.Order')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('phone', models.CharField(max_length=11, verbose_name='phone')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
            ],
        ),
    ]
