# Generated by Django 2.2.20 on 2021-10-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0022_ordercontactdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercontactdata',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pickupdelivery',
            name='name',
            field=models.CharField(max_length=64, verbose_name='contact person'),
        ),
        migrations.AlterField(
            model_name='toaddressdelivery',
            name='name',
            field=models.CharField(max_length=64, verbose_name='contact person'),
        ),
        migrations.AlterField(
            model_name='totcdelivery',
            name='name',
            field=models.CharField(max_length=64, verbose_name='contact person'),
        ),
    ]
