# Generated by Django 3.2.24 on 2024-03-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0024_auto_20231129_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Final price of the order to be paid by a customer including a delivery cost.', max_digits=12, null=True, verbose_name='final price of the order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Sum of all the products personal prices and their quantities.', max_digits=12, null=True, verbose_name='sum of all the products prices'),
        ),
        migrations.AlterField(
            model_name='orderproductmembership',
            name='personal_product_price',
            field=models.DecimalField(decimal_places=2, help_text='Personal product price at the moment of purchase', max_digits=12, verbose_name='personal product price'),
        ),
        migrations.AlterField(
            model_name='orderproductmembership',
            name='product_price',
            field=models.DecimalField(decimal_places=0, help_text='Product price at the moment of purchase', max_digits=12, verbose_name='product price'),
        ),
    ]
