# Generated by Django 3.2.25 on 2024-04-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0025_auto_20240313_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverycar',
            options={'ordering': ('position', 'carrying'), 'verbose_name': 'delivery car', 'verbose_name_plural': 'delivery cars'},
        ),
        migrations.AddField(
            model_name='deliverycar',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Выставление счета'), (1, 'Картой при получении'), (2, 'Наличными при получении'), (3, 'Онлайн'), (4, 'Кредит')], null=True, verbose_name='payment method'),
        ),
    ]
