# Generated by Django 3.2.25 on 2024-07-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0026_auto_20240417_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='yookassa_status',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='yookassa payment status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'выставление счета'), (1, 'картой при получении'), (2, 'наличными при получении'), (3, 'он-лайн'), (4, 'кредит'), (5, 'ЮКасса')], null=True, verbose_name='payment method'),
        ),
        migrations.CreateModel(
            name='YookassaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=32, unique=True, verbose_name='slug for confirm payment')),
                ('yookassa_id', models.CharField(blank=True, default='', max_length=32, verbose_name='ID payment into yookassa')),
                ('request_create', models.JSONField(verbose_name='Данные, которые отправили в юкассу')),
                ('response_create', models.JSONField(verbose_name='Данные, которые получили после создания платежа')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('waiting_for_capture', 'Waiting for capture'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled')], max_length=19, verbose_name='yookassa payment status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.order')),
            ],
            options={
                'verbose_name': 'yookassa payment',
                'verbose_name_plural': 'yookassa payments',
                'ordering': ('pk',),
            },
        ),
    ]
