# Generated by Django 3.2.25 on 2024-07-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0027_auto_20240718_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yookassadata',
            name='yookassa_id',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='ID payment into yookassa'),
        ),
    ]
