# Generated by Django 3.2.25 on 2025-03-03 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0028_alter_yookassadata_yookassa_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderExtraField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поля (для HTML)')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Название поля (Label)')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Комментарий перед полем')),
                ('field_type', models.CharField(choices=[('text', 'Текстовое поле'), ('textarea', 'Текстовая область'), ('select', 'Выпадающий список'), ('label', 'Метка (Label)')], max_length=20, verbose_name='Тип поля')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательное поле')),
                ('choices', models.TextField(blank=True, verbose_name='Значения списка (для select)')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция вывода')),
                ('css_class', models.CharField(blank=True, max_length=100, verbose_name='Дополнительный CSS класс')),
                ('binded_to', models.IntegerField(choices=[(1, 'Всегда'), (2, 'При самовывозе'), (3, 'При доставке'), (4, 'При доставке до ТК'), (5, 'При оплате через счет'), (6, 'При оплате картой при получении'), (7, 'При оплате наличными при получении'), (8, 'При оплате онлайн'), (9, 'При оплате в кредит'), (10, 'При оплате через Yookassa')], default=1, verbose_name='Привязка поля')),
            ],
            options={
                'verbose_name': 'Дополнительное поле',
                'verbose_name_plural': 'Дополнительные поля',
                'ordering': ['position'],
            },
        ),
        migrations.AlterModelOptions(
            name='yookassadata',
            options={'ordering': ('pk',), 'verbose_name': 'Yoomoney payment', 'verbose_name_plural': 'Yoomoney payments'},
        ),
        migrations.AlterField(
            model_name='yookassadata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.CreateModel(
            name='OrderExtraFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Значение')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.orderextrafield', verbose_name='Дополнительное поле')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_field_values', to='commerce.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Значение дополнительного поля',
                'verbose_name_plural': 'Значения дополнительных полей',
            },
        ),
    ]
