# Generated by Django 3.2.25 on 2025-03-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0029_auto_20250303_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderextrafield',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='метка внутри поля'),
        ),
        migrations.AlterField(
            model_name='orderextrafield',
            name='label',
            field=models.CharField(blank=True, max_length=200, verbose_name='метка перед полем'),
        ),
        migrations.AlterField(
            model_name='orderextrafield',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название поля'),
        ),
    ]
