# Generated by Django 3.2.25 on 2025-03-05
import json

from django.db import migrations, models


def upd_yookassa_logs(apps, *args, **kwargs):
    YookassaData = apps.get_model('commerce.YookassaData')
    for item in YookassaData.objects.all():
        if item.request_create:
            item.request_create = json.loads(item.request_create)
        if item.response_create:
            item.response_create = json.loads(item.response_create)
        item.save(update_fields=('request_create', 'response_create'))


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0030_auto_20250304_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yookassadata',
            options={
                'ordering': ('-created',),
                'verbose_name': 'Yoomoney payment',
                'verbose_name_plural': 'Yoomoney payments',
            },
        ),
        migrations.AddField(
            model_name='yookassadata',
            name='log',
            field=models.JSONField(blank=True, default=dict, verbose_name='логи проверки статуса'),
        ),
        migrations.RunPython(upd_yookassa_logs, migrations.RunPython.noop),
    ]
