# Generated by Django 3.2.25 on 2025-05-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0031_auto_20250305_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderextrafield',
            name='amocrm_field_id',
            field=models.PositiveIntegerField(blank=True, help_text='Привязка поля к полю в AMOcrm.', null=True, verbose_name='AMOcrm ID'),
        ),
        migrations.AlterField(
            model_name='orderextrafield',
            name='binded_to',
            field=models.IntegerField(choices=[(1, 'Всегда'), (2, 'При самовывозе'), (3, 'При доставке по адресу'), (4, 'При доставке до ТК'), (5, 'При оплате через счет'), (6, 'При оплате картой при получении'), (7, 'При оплате наличными при получении'), (8, 'При оплате онлайн'), (9, 'При оплате в кредит'), (10, 'При оплате через Yookassa')], default=1, verbose_name='Привязка поля'),
        ),
        migrations.AlterField(
            model_name='orderextrafield',
            name='required',
            field=models.BooleanField(default=False, help_text='работает только в полной корзине', verbose_name='Обязательное поле'),
        ),
    ]
