# Generated by Django 2.2.26 on 2022-04-11 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0058_auto_20220204_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoryAsParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Parameter')),
                ('parent_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='parent category')),
            ],
        ),
    ]
