# Generated by Django 2.2.26 on 2022-04-28 07:34

from django.db import migrations, models
import django.db.models.deletion


INITIAL_MAPPING = {
    'ЕА': '1',
    'МН': '3',
    'КУ': '5',
    'АА': '6',
    'ОТ': '7',
    'АВ': '8',
    'АЕ': '13',
    'ОК': '14',
    'МТ': '15'
}


def create_initials(apps, schema_editor):
    TicketStock = apps.get_model('smartlombard', 'TicketStock')
    Stock = apps.get_model('catalog', 'Stock')
    for k, v in INITIAL_MAPPING.items():
        try:
            stock = Stock.objects.get(third_party_code__iexact=v)
        except Exception:
            continue

        try:
            TicketStock.objects.create(stock=stock, code=k)
        except Exception:
            pass


def reverse_func(apps, schema_editor):
    TicketStock = apps.get_model('smartlombard', 'TicketStock')
    TicketStock.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0059_auto_20220428_0956'),
        ('smartlombard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='ticket stock code')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Stock', verbose_name='lombard_ticket_codes')),
            ],
            options={
                'verbose_name': 'ticket stock',
                'verbose_name_plural': 'ticket stocks',
                'unique_together': {('stock', 'code')},
            },
        ),
        migrations.RunPython(create_initials, reverse_func),
    ]
