# Generated by Django 2.2.26 on 2022-05-06 07:59

from django.db import migrations


def create_statictext(app, schema):
    try:
        Statictext = app.get_model('statictext', 'Statictext')
    except Exception:
        return

    Statictext.objects.create(
        key='lombard_oplata_text_top',
        text="""<h1>Онлайн оплата залога</h1>
<p>В данном разделе вы можете узнать сумму процентов или выкупа, а также произвести оплату не выходя из дома.</p>""",
        comment='Ломбард: текст для верхней части страницы оплаты.'
    )
    Statictext.objects.create(
        key='lombard_oplata_text_bottom',
        text='',
        comment='Ломбард: текст для нижней части страницы оплаты.'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('smartlombard', '0002_ticketstock'),
        ('statictext', '0015_no_category_or_products_text'),
    ]

    operations = [
        migrations.RunPython(create_statictext, ),
    ]
