# Generated by Django 3.2.13 on 2022-06-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlombard', '0003_lombard_online_payment_statictexts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('log', models.JSONField(blank=True, default=list, verbose_name='log data')),
            ],
            options={
                'verbose_name': 'update log',
                'verbose_name_plural': 'update logs',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='subcategoryasparameter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketstock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
