# Generated by Django 3.2.25 on 2024-10-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlombard', '0004_auto_20220601_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketstock',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Включение данной опции будет означать, что магазин с соответствующим кодом больше не работает.', verbose_name='отделение закрыто'),
        ),
        migrations.AddField(
            model_name='ticketstock',
            name='msg_for_closed',
            field=models.TextField(blank=True, help_text='Сообщение, отображаемое пользователю, когда отделение закрыто. Можно использовать HTML-теги.', null=True, verbose_name='сообщение для закрытого отделения'),
        ),
    ]
