# Generated by Django 3.2.25 on 2025-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlombard', '0005_auto_20241023_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBankPayment',
            fields=[
                ('payment_id', models.CharField(help_text='Назначается на стороне Т-Банка при инициализации платежа.', max_length=32, primary_key=True, serialize=False, verbose_name='Payment ID')),
                ('order_id', models.CharField(help_text='Номер(идентификатор) заказа на стороне сайта. Например при оплате залогового билета, этим номером будет номер билета.', max_length=32, verbose_name='Order ID')),
                ('amount', models.PositiveIntegerField(verbose_name='сумма в копейках')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата/время создания')),
                ('payment_url', models.URLField(verbose_name='url формы оплаты')),
                ('status', models.CharField(default='NEW', max_length=16, verbose_name='текущий статус')),
                ('log', models.JSONField(blank=True, default=dict, verbose_name='логи проверки статуса')),
            ],
            options={
                'verbose_name': 'платеж через т-банк',
                'verbose_name_plural': 'платежи через т-банк',
                'ordering': ('-created_at',),
            },
        ),
    ]
