# Generated by Django 3.2.25 on 2025-05-28

from django.db import migrations

from stroykerbox.apps.smartlombard.tbank import (
    TBANK_SUCCESS_URL,
    TBANK_FAIL_URL,
    TBANK_SUCCESS_URL_KEY,
    TBANK_FAIL_URL_KEY,
)


def forwards(apps, schema_editor):
    Page = apps.get_model('staticpages', 'Page')

    for item in (TBANK_SUCCESS_URL, TBANK_FAIL_URL):
        if item == TBANK_SUCCESS_URL:
            title = 'Платеж через Т-Банк успешно проведен'
            key = TBANK_SUCCESS_URL_KEY
        else:
            title = 'Платеж через Т-Банк не был проведен'
            key = TBANK_FAIL_URL_KEY

        Page.objects.create(
            text='',
            title=title,
            key=key,
            published=True,
            url=item,
            lft=0,
            rght=0,
            tree_id=0,
            level=0,
        )


def backwards(apps, schema_editor):
    apps.get_model('staticpages', 'Page').objects.filter(
        key__in=(TBANK_SUCCESS_URL_KEY, TBANK_FAIL_URL_KEY)
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('smartlombard', '0006_tbankpayment'),
        ('staticpages', '0014_auto_20230626_0734'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
