# Generated by Django 3.2.24 on 2024-02-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_forms', '0007_alter_customformfield_field_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFormFieldAMO',
            fields=[
                ('field_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='amocrm', serialize=False, to='custom_forms.customformfield', verbose_name='поле кастомной формы')),
                ('amo_id', models.PositiveIntegerField(verbose_name='ID поля в AMO CRM')),
            ],
            options={
                'verbose_name': 'id поля в amocrm',
                'verbose_name_plural': 'id полей в amocrm',
            },
        ),
    ]
