# Generated by Django 3.2.15 on 2023-05-31 16:02

from django.db import migrations, models
from django.core.management import call_command
import django.db.models.deletion


def create_vk_categories(apps, editor):
    call_command('update_vk_categories', verbosity=0)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0074_auto_20230526_2027'),
        ('vk_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VKCategory',
            fields=[
                ('id', models.PositiveIntegerField(
                    primary_key=True, serialize=False, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('section_id', models.PositiveIntegerField(
                    default=0, verbose_name='ID раздела')),
                ('section_name', models.CharField(
                    max_length=255, verbose_name='название раздела')),
            ],
            options={
                'verbose_name': 'категория vk-товара',
                'verbose_name_plural': 'категории vk-товаров',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VKProductMembership',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 primary_key=True, related_name='vk_product', serialize=False, to='catalog.product', editable=False)),
                ('vk_id', models.CharField(max_length=32, verbose_name='vk id', editable=False)),
            ],
            options={
                'verbose_name': 'связь товар/vk-товар',
                'verbose_name_plural': 'связи товар/vk-товар',
            },
        ),
        migrations.DeleteModel(
            name='VKtest',
        ),
        migrations.RunPython(create_vk_categories, migrations.RunPython.noop),
    ]
