# Generated by Django 3.2.20 on 2023-09-26 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0079_auto_20230912_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatPrice',
            fields=[
                ('product', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='floatprice', serialize=False, to='catalog.product')),
                ('price', models.DecimalField(decimal_places=2, help_text='Плавающая цена, которая будет заменять основную цену товара.', max_digits=12, verbose_name='плавающая цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата/время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата/время обновления')),
            ],
            options={
                'verbose_name': 'плавающая цена товара',
                'verbose_name_plural': 'плавающие цены товара',
                'ordering': ('-updated_at',),
            },
        ),
    ]
