# Generated by Django 3.2.20 on 2024-02-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floatprice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatprice',
            name='percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Собственный процент для формирования плавающей цены конкретного товара. Если не установлен - используется процент из глобальных настроек.', null=True, verbose_name='процент'),
        ),
    ]
