# Generated by Django 2.2.8 on 2019-12-10 21:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0016_order_invoicing_with_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmRequestBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='customer name')),
                ('phone', models.CharField(max_length=50, verbose_name='customer phone')),
                ('message', models.TextField(blank=True, null=True, verbose_name='customer message text')),
                ('manager_comment', models.TextField(blank=True, null=True, verbose_name='manager_comment')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='request date')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='changed')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'new'), (1, 'order created'), (2, 'canceled'), (3, 'call back later'), (4, 'completed')], db_index=True, default=0, verbose_name='status')),
                ('object_class', models.CharField(max_length=40)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='manager')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.Order')),
            ],
            options={
                'verbose_name': 'crm request',
                'verbose_name_plural': 'crm requests',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CallMeRequest',
            fields=[
                ('crmrequestbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.CrmRequestBase')),
            ],
            options={
                'verbose_name': 'call-me request',
                'verbose_name_plural': 'call-me requests',
                'ordering': ('-created',),
            },
            bases=('crm.crmrequestbase',),
        ),
        migrations.CreateModel(
            name='FeedbackMessageRequest',
            fields=[
                ('crmrequestbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.CrmRequestBase')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='customer email')),
                ('url', models.CharField(help_text='Relative url of the page from which the message was sent', max_length=255, validators=[django.core.validators.RegexValidator('^/([a-z0-9-_A-Z]+/#?)*$', message='Must start and end with a slash (/)')], verbose_name='url')),
                ('agree', models.BooleanField(default=False, null=True, verbose_name='personal data agreement')),
            ],
            options={
                'verbose_name': 'customer message',
                'verbose_name_plural': 'customer messages',
                'ordering': ('-created',),
            },
            bases=('crm.crmrequestbase',),
        ),
        migrations.CreateModel(
            name='FromCartRequest',
            fields=[
                ('crmrequestbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.CrmRequestBase')),
            ],
            options={
                'verbose_name': 'request from cart',
                'verbose_name_plural': 'requests from cart',
                'ordering': ('-created',),
            },
            bases=('crm.crmrequestbase',),
        ),
    ]
