# Generated by Django 2.2.9 on 2020-01-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20191227_1108'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmrequestbase',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Location'),
        ),
    ]
