# Generated by Django 2.2.11 on 2020-03-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_crmrequestbase_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmessagerequest',
            name='agree',
        ),
    ]
