# Generated by Django 2.2.20 on 2021-07-19 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_feedbackmessagerequest_agree'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftForPhoneRequest',
            fields=[
                ('crmrequestbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.CrmRequestBase')),
            ],
            options={
                'verbose_name': 'gift for phone request',
                'verbose_name_plural': 'gift for phone requests',
                'ordering': ('-created',),
            },
            bases=('crm.crmrequestbase',),
        ),
    ]
