# Generated by Django 2.2.20 on 2021-10-11 11:24

from django.db import migrations


def delete_reqs_without_orders(app, schema):
    FromCartRequest = app.get_model('crm', 'FromCartRequest')
    FromCartRequest.objects.filter(order__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_giftforphonerequest'),
    ]

    operations = [
        migrations.RunPython(delete_reqs_without_orders, migrations.RunPython.noop),
    ]
