# Generated by Django 3.2.15 on 2023-01-10 18:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_alter_location_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0005_remove_crm_from_cart_reqs_without_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callmerequest',
            options={'ordering': ('-created',), 'verbose_name': 'запрос обратного звонка', 'verbose_name_plural': 'запросы обратных звонков'},
        ),
        migrations.AlterModelOptions(
            name='crmrequestbase',
            options={'ordering': ('-created',), 'verbose_name': 'запрос от клиента', 'verbose_name_plural': 'запросы от клиентов'},
        ),
        migrations.AlterModelOptions(
            name='feedbackmessagerequest',
            options={'ordering': ('-created',), 'verbose_name': 'сообщение клиента', 'verbose_name_plural': 'сообщения клиента'},
        ),
        migrations.AlterModelOptions(
            name='fromcartrequest',
            options={'ordering': ('-created',), 'verbose_name': 'заказ через корзину', 'verbose_name_plural': 'заказы через корзину'},
        ),
        migrations.AlterModelOptions(
            name='giftforphonerequest',
            options={'ordering': ('-created',), 'verbose_name': 'запрос на подарок за телефон', 'verbose_name_plural': 'запросы на подарок за телефон'},
        ),
        migrations.AlterField(
            model_name='crmrequestbase',
            name='changed',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='crmrequestbase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата запроса'),
        ),
        migrations.AlterField(
            model_name='crmrequestbase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crmrequestbase',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
        migrations.AlterField(
            model_name='crmrequestbase',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='менеджер'),
        ),
        migrations.AlterField(
            model_name='crmrequestbase',
            name='manager_comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий менеджера'),
        ),
        migrations.AlterField(
            model_name='crmrequestbase',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='сообщение клиента'),
        ),
        migrations.AlterField(
            model_name='crmrequestbase',
            name='name',
            field=models.CharField(max_length=255, verbose_name='имя клиента'),
        ),
        migrations.AlterField(
            model_name='crmrequestbase',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='телефон клиента'),
        ),
        migrations.AlterField(
            model_name='crmrequestbase',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'новый'), (1, 'создан заказ'), (2, 'отмена'), (3, 'перезвонить позже'), (4, 'завершен')], db_index=True, default=0, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='feedbackmessagerequest',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email клиента'),
        ),
        migrations.AlterField(
            model_name='feedbackmessagerequest',
            name='url',
            field=models.CharField(help_text='Относительный url страницы, с которой было отправлено сообщение', max_length=255, validators=[django.core.validators.RegexValidator('^/([a-z0-9-_A-Z]+/#?)*$', message='Долно начинаться и заканчиваться слэшем (/)')], verbose_name='url'),
        ),
    ]
