# Generated by Django 3.2.25 on 2024-10-16

from django.db import migrations, models


# def migrate_url_field(app, schema):
#     FeedbackMessageRequest = app.get_model('crm', 'FeedbackMessageRequest')
#     FeedbackMessageRequest.objects.exclude(url='').update(page_url=models.F('url'))


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20230110_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmrequestbase',
            name='page_url',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='страница отправки формы'),
        ),
        migrations.AddField(
            model_name='crmrequestbase',
            name='utm_campaign',
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name='метка utm_campaign'),
        ),
        migrations.AddField(
            model_name='crmrequestbase',
            name='utm_content',
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name='метка utm_content'),
        ),
        migrations.AddField(
            model_name='crmrequestbase',
            name='utm_medium',
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name='метка utm_medium'),
        ),
        migrations.AddField(
            model_name='crmrequestbase',
            name='utm_source',
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name='метка utm_source'),
        ),
        migrations.AddField(
            model_name='crmrequestbase',
            name='utm_term',
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name='метка utm_term'),
        ),
        # migrations.RunPython(migrate_url_field, migrations.RunPython.noop),
    ]
