# Generated by Django 3.2.25 on 2024-10-16

from django.db import migrations


def migrate_url_field(app, schema):
    FeedbackMessageRequest = app.get_model('crm', 'FeedbackMessageRequest')
    for obj in FeedbackMessageRequest.objects.all():
        if getattr(obj, 'url', None):
            obj.page_url = obj.url
            obj.save(update_fields=('page_url',))


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20241016_1847'),
    ]

    operations = [
        migrations.RunPython(migrate_url_field, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='feedbackmessagerequest',
            name='url',
        ),
    ]
