# Generated by Django 2.2.17 on 2020-11-12 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0005_auto_20201013_1957'),
        ('catalog', '0044_auto_20201107_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_source_url', models.URLField(max_length=1024, verbose_name='source url')),
                ('filter_option_selector', models.CharField(max_length=50, verbose_name='filter option selector')),
                ('filter_json_attr', models.CharField(blank=True, max_length=50, null=True, verbose_name='filter json data attribute')),
                ('filter_option_title_selector', models.CharField(max_length=50, verbose_name='filter option title selector')),
                ('filter_option_checkbox_selector', models.CharField(max_length=50, verbose_name='filter option checkbox selector')),
                ('filter_option_range_selector', models.CharField(max_length=50, verbose_name='filter option range selector')),
                ('pagination_selector', models.CharField(blank=True, max_length=50, null=True, verbose_name='pagination item selector')),
                ('page_prefix', models.CharField(blank=True, max_length=50, null=True, verbose_name='page prefix')),
                ('product_url_selector', models.CharField(max_length=50, verbose_name='product url selector')),
                ('product_code_selector', models.CharField(blank=True, max_length=50, null=True, verbose_name='product code selector')),
                ('product_price_selector', models.CharField(max_length=50, verbose_name='price selector')),
                ('product_name_selector', models.CharField(max_length=50, verbose_name='product name selector')),
                ('product_description_selector', models.CharField(max_length=50, verbose_name='product description selector')),
                ('product_inline_params_selector', models.CharField(max_length=50, verbose_name='product inline params selector')),
                ('product_inline_params_map', models.CharField(max_length=255, verbose_name='product inline params map')),
                ('product_image_selector', models.CharField(blank=True, max_length=50, null=True, verbose_name='product image selector')),
                ('product_image_src_attr', models.CharField(blank=True, max_length=50, null=True, verbose_name='product image src attribute')),
                ('product_old_images_delete', models.BooleanField(default=True, verbose_name='delete product old images')),
                ('product_uom_name', models.CharField(max_length=20, verbose_name='product unit name')),
                ('product_published', models.BooleanField(default=False, verbose_name='product published')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.Partner')),
            ],
            options={
                'verbose_name': 'scraper',
                'verbose_name_plural': 'scrapers',
                'unique_together': {('category', 'partner')},
            },
        ),
    ]
