# Generated by Django 2.2.17 on 2020-11-12 11:28

from logging import getLogger
from django.db import migrations, Error


logger = getLogger('django')


def forwards(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    try:
        Scraper = apps.get_model('scraper.Scraper')
        Scraper.objects.update_or_create(
            category_source_url='https://samara.kuvalda.ru/catalog/2023/',
            filter_option_selector='catalog-filter',
            filter_json_attr='json-data',
            filter_option_title_selector='.filter-option__title',
            filter_option_checkbox_selector='.filter-checkbox__link, .filter-checkbox__label',
            filter_option_range_selector='.filter-range',
            pagination_selector='.pagination__item',
            page_prefix='page-',
            product_url_selector='.catalog__list-item .link',
            product_code_selector='.product-header__code-title',
            product_price_selector='.product-buy__price-value span',
            product_name_selector='.page-header__title',
            product_description_selector='.product-specs__descr',
            product_inline_params_selector='.product-specs__table',
            product_inline_params_map='{"Мощность двигателя": ["л.с."], "Ширина захвата": ["см"], "Высота захвата": ["см"], "Дальность выброса снега": ["от", "до", "м", "мм", "см"]}',
            product_image_selector='.product-gallery__slider-image',
            product_image_src_attr='data-src',
            product_old_images_delete=True,
            product_uom_name='шт',
            product_published=False,
        )
    except Error as e:
        logger.error(str(e))


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
    ]
