# Generated by Django 2.2.17 on 2020-11-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20201112_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='filter_parameter_names_to_walk',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='filter parameter names to walk'),
        ),
    ]
