# Generated by Django 2.2.17 on 2020-11-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scraper_filter_parameter_names_to_walk'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='filter_product_to_walk_selector',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='filter product to walk selector'),
        ),
    ]
