# Generated by Django 2.2.17 on 2020-11-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_scraper_filter_product_to_walk_selector'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='product_parameter_values_to_join',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='parameter values to join'),
        ),
    ]
