# Generated by Django 2.2.17 on 2021-02-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_scraper_product_parameter_values_to_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='product_params_clear',
            field=models.BooleanField(default=True, verbose_name='clear params of existed products'),
        ),
    ]
