# Generated by Django 2.2.17 on 2021-02-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_scraper_product_params_clear'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='product_parameters_to_join',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='parameters to join'),
        ),
    ]
