# Generated by Django 2.2.17 on 2021-02-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_scraper_product_parameters_to_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='filter_option_range_selector',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='filter option range selector'),
        ),
    ]
