# Generated by Django 2.2.20 on 2021-06-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_auto_20210228_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='parameters_to_parse',
            field=models.CharField(max_length=255, null=True, verbose_name='parameters to parse'),
        ),
    ]
