# Generated by Django 3.2.15 on 2023-05-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovofonCall',
            fields=[
                ('id', models.CharField(help_text='Совпадает с ID Новофона.', max_length=16, primary_key=True, serialize=False)),
                ('call_dt', models.DateTimeField(verbose_name='дата/время звонка')),
                ('sip', models.CharField(blank=True, max_length=16, null=True)),
                ('number_from', models.CharField(help_text='С какого номера звонили.', max_length=16, verbose_name='from')),
                ('number_to', models.CharField(help_text='Куда звонили.', max_length=16, verbose_name='to')),
                ('disposition', models.CharField(max_length=24, verbose_name='состояние звонка')),
                ('billseconds', models.PositiveIntegerField(verbose_name='количество секунд звонка')),
                ('call_type', models.CharField(blank=True, choices=[('outgoing', 'исходящий'), ('incoming', 'входящий')], max_length=11, null=True, verbose_name='тип звонка')),
            ],
            options={
                'verbose_name': 'звонок через Новофон',
                'verbose_name_plural': 'звонки через Новофон',
                'ordering': ('-call_dt',),
            },
        ),
    ]
