# Generated by Django 3.2.15 on 2023-05-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novofon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novofoncall',
            name='id',
            field=models.CharField(help_text='Совпадает с ID Новофона.', max_length=64, primary_key=True, serialize=False),
        ),
    ]
