# Generated by Django 3.2.20 on 2024-02-05 22:42

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSet',
            fields=[
                ('key', models.SlugField(help_text='The value should only consist of Latin letters, numbers, underscores or hyphens.', max_length=70, primary_key=True, serialize=False, verbose_name='ключ')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('hours_range', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, help_text='Если диапазон не выбран - матрица будет считаться, как выбранной для резерва дней.', null=True, validators=[django.contrib.postgres.validators.RangeMinValueValidator(0), django.contrib.postgres.validators.RangeMaxValueValidator(23)], verbose_name='диапазон часов')),
                ('published', models.BooleanField(default=True, verbose_name='опубликована')),
            ],
            options={
                'verbose_name': 'набор слотов брони',
                'verbose_name_plural': 'наборы слотов брони',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название слота')),
                ('itemset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.itemset', verbose_name='набор слотов')),
            ],
            options={
                'verbose_name': 'слот брони',
                'verbose_name_plural': 'слоты брони',
                'unique_together': {('itemset', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ItemReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('hour', models.PositiveIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)], null=True, verbose_name='час')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='комментарий')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='booking.item')),
            ],
            options={
                'verbose_name': 'бронирование',
                'verbose_name_plural': 'бронирования',
                'unique_together': {('item', 'date', 'hour')},
            },
        ),
    ]
