# Generated by Django 3.2.24 on 2024-03-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreserve',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='itemreserve',
            name='phone',
            field=models.CharField(max_length=18, null=True, verbose_name='телефон для связи'),
        ),
    ]
