# Generated by Django 3.2.24 on 2024-03-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20240314_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemset',
            name='html_bottom',
            field=models.TextField(blank=True, null=True, verbose_name='html после формы'),
        ),
        migrations.AddField(
            model_name='itemset',
            name='html_middle',
            field=models.TextField(blank=True, null=True, verbose_name='html после таблицы'),
        ),
        migrations.AddField(
            model_name='itemset',
            name='html_top',
            field=models.TextField(blank=True, null=True, verbose_name='html перед таблицей'),
        ),
    ]
