# Generated by Django 3.2.25 on 2024-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20240315_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreserve',
            name='no_notify',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='itemset',
            name='slots_ahead',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Кол-во слотов, рассположенных за выбранным, и бронируемых вместе с выбранным.', null=True, verbose_name='кол-во бронирований вперед'),
        ),
    ]
