# Generated by Django 3.2.25 on 2024-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20240608_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemset',
            name='form_text',
            field=models.TextField(blank=True, null=True, verbose_name='текс формы заказа'),
        ),
        migrations.AddField(
            model_name='itemset',
            name='form_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок формы заказа'),
        ),
    ]
