# Generated by Django 2.2.26 on 2022-04-14 13:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomForm',
            fields=[
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('key', models.SlugField(primary_key=True, serialize=False, verbose_name='key')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'custom form',
                'verbose_name_plural': 'custom forms',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='CustomFormResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', django.db.models.JSONField(default=dict, verbose_name='results')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_forms.CustomForm')),
            ],
            options={
                'verbose_name': 'custom form result',
                'verbose_name_plural': 'custom form results',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CustomFormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_class', models.CharField(choices=[('stroykerbox.apps.custom_forms.fields.TextareaField', 'multiline text'), ('django.forms.CharField', 'text string'), ('django.forms.URLField', 'url'), ('django.forms.EmailField', 'email'), ('stroykerbox.apps.custom_forms.fields.PhoneField', 'phone'), ('django.forms.FloatField', 'float'), ('django.forms.IntegerField', 'integer'), ('django.forms.BooleanField', 'boolean'), ('stroykerbox.apps.custom_forms.fields.DateField', 'date'), ('django.forms.FileField', 'file')], max_length=128, verbose_name='form field class')),
                ('label', models.CharField(max_length=32, verbose_name='field label')),
                ('show_label', models.BooleanField(default=True, verbose_name='show label')),
                ('html_name', models.SlugField(help_text='Field name for html form.', verbose_name='html name')),
                ('placeholder', models.CharField(blank=True, max_length=64, null=True, verbose_name='field placeholder')),
                ('css_classes', models.CharField(blank=True, help_text='CSS class(es) for the field. Separate by space.', max_length=256, null=True, verbose_name='css classes')),
                ('required', models.BooleanField(default=True, verbose_name='field is required')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='custom_forms.CustomForm')),
            ],
            options={
                'verbose_name': 'custom form field',
                'verbose_name_plural': 'custom form fields',
                'ordering': ('position',),
            },
        ),
    ]
