# Generated by Django 3.2.15 on 2022-12-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='telegram_chat_id',
            field=models.IntegerField(blank=True, help_text='ID чата в Телеграм, куда отправлять уведомления о заполнениях формы. Если не указано, тогда используется chat_id из глобальных настроек.', null=True, verbose_name='telegram chat_id'),
        ),
        migrations.AlterField(
            model_name='customformfield',
            name='field_class',
            field=models.CharField(choices=[('django.forms.FloatField', 'float'), ('django.forms.EmailField', 'email'), ('django.forms.BooleanField', 'boolean'), ('django.forms.IntegerField', 'integer'), ('django.forms.URLField', 'url'), ('stroykerbox.apps.custom_forms.fields.TextareaField', 'multiline text'), ('django.forms.CharField', 'text string'), ('stroykerbox.apps.custom_forms.fields.DateField', 'date'), ('django.forms.FileField', 'file'), ('stroykerbox.apps.custom_forms.fields.PhoneField', 'phone')], max_length=128, verbose_name='form field class'),
        ),
        migrations.AlterField(
            model_name='customformfield',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customformresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
