# Generated by Django 3.2.15 on 2022-12-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0002_auto_20221210_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customform',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='ID чата в Телеграм, куда отправлять уведомления о заполнениях формы. Если не указано, тогда используется chat_id из глобальных настроек.', null=True, verbose_name='telegram chat_id'),
        ),
        migrations.AlterField(
            model_name='customformfield',
            name='field_class',
            field=models.CharField(choices=[('django.forms.FloatField', 'float'), ('django.forms.FileField', 'file'), ('django.forms.IntegerField', 'integer'), ('stroykerbox.apps.custom_forms.fields.PhoneField', 'phone'), ('django.forms.EmailField', 'email'), ('django.forms.CharField', 'text string'), ('stroykerbox.apps.custom_forms.fields.TextareaField', 'multiline text'), ('django.forms.BooleanField', 'boolean'), ('stroykerbox.apps.custom_forms.fields.DateField', 'date'), ('django.forms.URLField', 'url')], max_length=128, verbose_name='form field class'),
        ),
    ]
