# Generated by Django 3.2.15 on 2023-05-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_locationphone'),
        ('custom_forms', '0003_auto_20221212_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='customformresult',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
        migrations.AlterField(
            model_name='customformfield',
            name='field_class',
            field=models.CharField(choices=[('stroykerbox.apps.custom_forms.fields.PhoneField', 'phone'), ('django.forms.BooleanField', 'boolean'), ('stroykerbox.apps.custom_forms.fields.TextareaField', 'multiline text'), ('django.forms.FloatField', 'float'), ('stroykerbox.apps.custom_forms.fields.DateField', 'date'), ('django.forms.EmailField', 'email'), ('django.forms.CharField', 'text string'), ('django.forms.IntegerField', 'integer'), ('django.forms.FileField', 'file'), ('django.forms.URLField', 'url')], max_length=128, verbose_name='form field class'),
        ),
    ]
