# Generated by Django 3.2.15 on 2023-07-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0004_auto_20230515_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='metrica_goal',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='имя цели для я-метрики'),
        ),
        migrations.AlterField(
            model_name='customformfield',
            name='field_class',
            field=models.CharField(choices=[('django.forms.CharField', 'text string'), ('django.forms.EmailField', 'email'), ('django.forms.BooleanField', 'boolean'), ('stroykerbox.apps.custom_forms.fields.TextareaField', 'multiline text'), ('django.forms.FloatField', 'float'), ('django.forms.FileField', 'file'), ('stroykerbox.apps.custom_forms.fields.DateField', 'date'), ('stroykerbox.apps.custom_forms.fields.PhoneField', 'phone'), ('django.forms.IntegerField', 'integer'), ('django.forms.URLField', 'url')], max_length=128, verbose_name='form field class'),
        ),
    ]
