# Generated by Django 3.2.20 on 2023-11-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0005_auto_20230728_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSelectFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Field name from custom forms', unique=True, verbose_name='html name')),
            ],
            options={
                'verbose_name': 'custom select field',
                'verbose_name_plural': 'custom select fields',
                'ordering': ('key', 'pk'),
            },
        ),
        migrations.AlterField(
            model_name='customformfield',
            name='field_class',
            field=models.CharField(choices=[('stroykerbox.apps.custom_forms.fields.PhoneField', 'phone'), ('stroykerbox.apps.custom_forms.fields.FileField', 'multiple files'), ('stroykerbox.apps.custom_forms.fields.PseudoFileField', 'multiple files with preload'), ('stroykerbox.apps.custom_forms.fields.TextareaField', 'multiline text'), ('django.forms.FileField', 'file'), ('stroykerbox.apps.custom_forms.fields.DateField', 'date'), ('django.forms.CharField', 'text string'), ('django.forms.IntegerField', 'integer'), ('stroykerbox.apps.custom_forms.fields.SelectField', 'select field'), ('django.forms.URLField', 'url'), ('django.forms.FloatField', 'float'), ('django.forms.EmailField', 'email'), ('django.forms.BooleanField', 'boolean')], max_length=128, verbose_name='form field class'),
        ),
        migrations.CreateModel(
            name='CustomSelectFieldChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='value')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='custom_forms.customselectfieldmodel')),
            ],
            options={
                'verbose_name': 'custom choice of select field',
                'verbose_name_plural': 'custom choices of select field',
                'ordering': ('position', 'value'),
            },
        ),
    ]
