# Generated by Django 3.2.24 on 2024-02-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0006_auto_20231101_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customformfield',
            name='field_class',
            field=models.CharField(choices=[('django.forms.CharField', 'text string'), ('django.forms.BooleanField', 'boolean'), ('django.forms.EmailField', 'email'), ('stroykerbox.apps.custom_forms.fields.PseudoFileField', 'multiple files with preload'), ('django.forms.URLField', 'url'), ('django.forms.IntegerField', 'integer'), ('stroykerbox.apps.custom_forms.fields.TextareaField', 'multiline text'), ('django.forms.FileField', 'file'), ('django.forms.FloatField', 'float'), ('stroykerbox.apps.custom_forms.fields.DateField', 'date'), ('stroykerbox.apps.custom_forms.fields.SelectField', 'select field'), ('stroykerbox.apps.custom_forms.fields.FileField', 'multiple files'), ('stroykerbox.apps.custom_forms.fields.PhoneField', 'phone')], max_length=128, verbose_name='form field class'),
        ),
    ]
