# Generated by Django 3.2.25 on 2024-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0007_alter_customformfield_field_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='customformresult',
            name='page_url',
            field=models.URLField(blank=True, help_text='URL страницы, с которой была отправлена форма.',
                                  null=True, verbose_name='url страницы отправки'),
        ),
        migrations.AlterField(
            model_name='customformfield',
            name='field_class',
            field=models.CharField(choices=[('django.forms.EmailField', 'email'), ('stroykerbox.apps.custom_forms.fields.DateField', 'date'), ('django.forms.BooleanField', 'boolean'), ('stroykerbox.apps.custom_forms.fields.TextareaField', 'multiline text'), ('stroykerbox.apps.custom_forms.fields.PhoneField', 'phone'), ('django.forms.CharField', 'text string'), ('django.forms.URLField', 'url'), (
                'django.forms.FileField', 'file'), ('stroykerbox.apps.custom_forms.fields.PseudoFileField', 'multiple files with preload'), ('django.forms.IntegerField', 'integer'), ('stroykerbox.apps.custom_forms.fields.FileField', 'multiple files'), ('stroykerbox.apps.custom_forms.fields.SelectField', 'select field'), ('django.forms.FloatField', 'float')], max_length=128, verbose_name='form field class'),
        ),
    ]
