# Generated by Django 3.2.25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='дата/время запроса')),
                ('response_ms', models.PositiveIntegerField(default=0)),
                ('path', models.CharField(max_length=256, verbose_name='URL запроса')),
                ('view', models.CharField(blank=True, max_length=128, null=True)),
                ('view_method', models.CharField(blank=True, max_length=128, null=True)),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='данные запроса')),
                ('response', models.TextField(blank=True, null=True, verbose_name='данные ответа')),
                ('query_params', models.JSONField(blank=True, default=dict, verbose_name='get-параметры')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('host', models.URLField()),
                ('method', models.CharField(max_length=10)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('errors', models.TextField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Request Log',
                'ordering': ('-requested_at',),
            },
        ),
    ]
