# Generated by Django 2.2.7 on 2019-11-09 12:04

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(unique=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='news', verbose_name='image')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('teaser', models.TextField(verbose_name='teaser text')),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'news item',
                'verbose_name_plural': 'news',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140, null=True, verbose_name='title')),
                ('image', models.FileField(upload_to='news', verbose_name='image')),
                ('position', models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='position')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.News')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'ordering': ['position', 'id'],
            },
        ),
    ]
