# Generated by Django 2.2.7 on 2019-11-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='post_type',
            field=models.CharField(choices=[('news', 'news'), ('promo', 'promo')], default='news', max_length=7, verbose_name='post type'),
        ),
    ]
