# Generated by Django 2.2.7 on 2019-11-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_post_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date', '-pk'], 'verbose_name': 'news/promo item', 'verbose_name_plural': 'news/promo items'},
        ),
        migrations.AlterField(
            model_name='news',
            name='post_type',
            field=models.CharField(choices=[('news', 'news'), ('promo', 'promo')], default='news', help_text='Type of publication - news or promotion.', max_length=7, verbose_name='post type'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_newsimage_attach', to='news.News'),
        ),
        migrations.CreateModel(
            name='NewsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140, null=True, verbose_name='title')),
                ('position', models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='position')),
                ('file', models.FileField(upload_to='news', verbose_name='file')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_newsfile_attach', to='news.News')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
                'ordering': ['position', 'id'],
            },
        ),
    ]
