# Generated by Django 2.2.7 on 2019-11-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191112_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='wide_view',
            field=models.BooleanField(default=False, verbose_name='wide view mode'),
        ),
    ]
