# Generated by Django 2.2.7 on 2019-11-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_wide_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='show on the site'),
        ),
    ]
