# Generated by Django 2.2.7 on 2019-11-25 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsfile',
            options={'default_related_name': 'files', 'ordering': ['position', 'id'], 'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'default_related_name': 'images', 'ordering': ['position', 'id'], 'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AlterField(
            model_name='newsfile',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='news.News'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.News'),
        ),
    ]
