# Generated by Django 2.2.11 on 2020-04-07 10:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20191125_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='teaser',
            field=ckeditor.fields.RichTextField(verbose_name='teaser text'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='text'),
        ),
    ]
