# Generated by Django 3.2.13 on 2022-09-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200407_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='use_custom_form',
            field=models.BooleanField(default=False, help_text='Uses the custom form inside text. To insert the desired custom form use the syntax: {% custom_form "CUSTOM-FORM-KEY" %}', verbose_name='use custom form'),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newsfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
