# Generated by Django 3.2.15 on 2023-01-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20220914_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='meta keywords'),
        ),
    ]
