# Generated by Django 3.2.15 on 2023-02-28 12:38

from django.db import migrations
from constance import config


def upd_phone_settings(app, schema):
    second_phone = getattr(config, 'SITE_DEFAULT_PHONE_SECOND', '') or ''
    try:
        setattr(config, 'SITE_PHONES', second_phone)
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(upd_phone_settings, migrations.RunPython.noop),
    ]
