# Generated by Django 2.2.9 on 2019-12-26 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_geoip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='location name')),
                ('is_default', models.BooleanField(default=False, help_text='Set this location as default.')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this location.')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='location', to='django_geoip.City')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
    ]
