# Generated by Django 2.2.9 on 2019-12-27 08:08

from django.db import migrations, models
from uuslug import slugify


def set_slugs(apps, schema_editor):
    Location = apps.get_model('locations', 'Location')
    for location in Location.objects.all():
        location.slug = slugify(location.city.name)
        location.save()


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_slug'),
    ]

    operations = [
        migrations.RunPython(set_slugs,),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='slug'),
        ),
    ]
