# Generated by Django 2.2.11 on 2020-03-12 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20191227_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^7[\\d]{10}$', 'Enter a valid phone number starting with "7" followed by 10 digits.', 'invalid')], verbose_name='contact phone'),
        ),
    ]
