# Generated by Django 2.2.12 on 2020-10-13 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_location_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[78][\\d]{10}$', 'Enter a valid phone number starting with "7 (or 8)" followed by 10 digits.', 'invalid')], verbose_name='contact phone'),
        ),
    ]
