# Generated by Django 2.2.20 on 2022-01-04 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20210728_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='contact_phone_second',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[78][\\d]{10}$', 'Enter a valid phone number starting with "7 (or 8)" followed by 10 digits.', 'invalid')], verbose_name='contact phone second'),
        ),
    ]
