# Generated by Django 3.2.15 on 2022-10-10 15:31

from django.db import migrations
from django.core.management import call_command


def load_fixtures_with_default_geo_data(apps, schema_editor):
    try:
        # try import
        import django_geoip  # noqa
        # try city model exists
        City = apps.get_model('django_geoip.city')
    except Exception:
        return

    if not City.objects.all().exists():
        call_command('loaddata', 'django_geoip_app_data.json',
                     app_label='locations')
                     # app_label='django_geoip')


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_location_contact_phone_second'),
    ]

    operations = [
        migrations.RunPython(
            load_fixtures_with_default_geo_data, migrations.RunPython.noop),
    ]
