# Generated by Django 3.2.15 on 2023-03-13 11:31
import re

from django.db import migrations, models
import django.db.models.deletion


def clear_phone(phone):
    return re.sub(r'[^\d\+]', '', phone)


def phones_migrate(apps, schema_editor):
    Location = apps.get_model('locations', 'Location')
    LocationPhone = apps.get_model('locations', 'LocationPhone')
    for location in Location.objects.all():
        if location.contact_phone:
            LocationPhone.objects.create(
                location=location,
                phone=location.contact_phone,
                phone_raw=clear_phone(location.contact_phone)
            )

        if location.contact_phone_second:
            LocationPhone.objects.create(
                location=location,
                phone=location.contact_phone_second,
                phone_raw=clear_phone(location.contact_phone_second),
                position=1
            )


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_alter_location_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(
                    max_length=32, verbose_name='formated phone')),
                ('phone_raw', models.CharField(
                    max_length=16, verbose_name='phone for url')),
                ('position', models.PositiveSmallIntegerField(
                    default=0, verbose_name='position')),
                ('location', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='locations.location')),
            ],
            options={
                'verbose_name': 'location phone',
                'verbose_name_plural': 'location phones',
                'ordering': ('position',),
            },
        ),
        migrations.RunPython(phones_migrate, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='location',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='location',
            name='contact_phone_second',
        ),
    ]
