# Generated by Django 3.2.20 on 2023-11-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_locationphone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('position', 'pk'), 'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
        migrations.AddField(
            model_name='location',
            name='position',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='position'),
        ),
    ]
