# Generated by Django 3.2.25 on 2025-11-10

from django.db import migrations


def update_images(apps, *args, **kwargs):
    for i in apps.get_model('catalog', 'ProductImage').objects.all():
        try:
            i.update_file_size_value()
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0095_auto_20250818'),
    ]

    operations = [
        migrations.RunPython(update_images, reverse_code=migrations.RunPython.noop)
    ]
