# Generated by Django 2.2.6 on 2019-11-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statictext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='This value is used in the code. Do not touch it!', max_length=70, unique=True, verbose_name='key')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'static text',
                'verbose_name_plural': 'static texts',
            },
        ),
    ]
