# Generated by Django 2.2.6 on 2019-11-01 10:08

from django.db import migrations


def create_recipient_billing_details_entry(apps, schema_editor):
    Statictext = apps.get_model('statictext', 'Statictext')
    Statictext.objects.create(key='recipient_billing_details',
                              text='',
                              comment='Beneficiary billing details when invoicing an order.'
                              )


class Migration(migrations.Migration):

    dependencies = [
        ('statictext', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_recipient_billing_details_entry, ),
    ]
