# Generated by Django 2.2.8 on 2019-12-24 12:28

import ckeditor.fields
from django.db import migrations
from django.urls import reverse


def create_call_for_registration(apps, schema_editor):
    register_url = reverse('registration')
    Statictext = apps.get_model('statictext', 'Statictext')
    Statictext.objects.create(key='call_for_registration',
                              text=f'Для использования функционала сайта в полной мере'
                              f' <a href="{register_url}">необходима регистрация</a>',
                              comment='Text with calls to register on the site.'
                              )


class Migration(migrations.Migration):

    dependencies = [
        ('statictext', '0002_recipient_billing_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statictext',
            name='text',
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name='text'),
        ),
        migrations.RunPython(create_call_for_registration, ),
    ]
