# Generated by Django 2.2.9 on 2019-12-28 10:12

from django.db import migrations


def create_text_for_partnerlist_page_header(apps, schema_editor):
    Statictext = apps.get_model('statictext', 'Statictext')
    Statictext.objects.create(key='partner_listpage_header',
                              text=f'<h1>Партнерская сеть</h1>'
                              f'<p>Продукцию вы можете купить у одного из наших партнеров.</p>',
                              comment='Text for the header of the page with the list of partners.'
                              )


class Migration(migrations.Migration):

    dependencies = [
        ('statictext', '0003_auto_20191224_1528'),
    ]

    operations = [
        migrations.RunPython(create_text_for_partnerlist_page_header, ),
    ]
