# Generated by Django 2.2.11 on 2020-03-07 19:44

from django.db import migrations
from django.templatetags.static import static


def create_new_items(apps, schema_editor):
    Statictext = apps.get_model('statictext', 'Statictext')
    Statictext.objects.create(key='frontpage_seo_text',
                              text='<h2>Что такое Дисториум</h2>'
                              '<p>Инвестируем в заводы, производящие листовые строительные материалы (ДСП ЦСП ФАНЕРА, ОСБ и т.д.) заключаем договора, выкупаем партии продукции, везем вагонами или фурами на склад и после поставляют постоянным клиентам типа “Красной цены”, “Сатурна”, “Центр строя” и т.д. Если есть товар в наличии и их цена ниже, то мы продаем, если нет — то продают конкуренты. Заключаем договора, выкупаем партии продукции, везем вагонами или фурами на склад и после поставляют постоянным клиентам типа “Красной цены”, “Сатурна”, “Центр строя” и т.д. Если есть товар в наличии и их цена ниже, то мы продаем, если нет — то продают конкуренты.</p>',
                              comment='Frontpage seo-text'
                              )

    map_image = static('images/map-exmple.jpg')
    Statictext.objects.create(key='map_block',
                              text= f'<div class="map"><img src="{map_image}" alt=""></div>',
                              comment='Block with map (as image)'
                              )


class Migration(migrations.Migration):

    dependencies = [
        ('statictext', '0004_text_for_partners_listpage_header'),
    ]

    operations = [
        migrations.RunPython(create_new_items, ),
    ]
