# Generated by Django 2.2.11 on 2020-03-11 18:32

from django.db import migrations


def create_text(apps, schema_editor):
    Statictext = apps.get_model('statictext', 'Statictext')
    Statictext.objects.create(key='form_agreement_text',
                              text='<span class="form-text">Нажимая на кнопку, '
                              'вы даете согласие на обработку персональных данных '
                              'и соглашаетесь с нашей политикой конфиденциальности</span>',
                              comment='The text of the agreement on the processing of personal data.'
                              )


class Migration(migrations.Migration):

    dependencies = [
        ('statictext', '0005_frontpage_seo_text_and_map_block'),
    ]

    operations = [
        migrations.RunPython(create_text, ),
    ]
