# Generated by Django 2.2.11 on 2020-03-18 10:17

from django.db import migrations


def create_text(apps, schema_editor):
    Statictext = apps.get_model('statictext', 'Statictext')
    Statictext.objects.create(key='club_privileges_block',
                              text="""
<span class="content-title center">Ваши привилегии клуба Дисториум</span>
<div class="privilege-block">
    <div class="privilege-item">
        <span class="privilege-item__title">Калькулятор доставки</span>
        <p>Откройте для себя наш удобный инструмент для рассчета стоимости доставки</p>
        <a href="/cart/delivery_calculator/" class="btn-calculate"><span class="icon"><svg class="icon">
                    <use xlink:href="#delivery-white"></use>
                </svg></span>Рассчитать</a>
    </div>
    <div class="privilege-item">
        <span class="privilege-item__title">Экономьте свое время</span>
        <p>Выставите счет в корзине или отправьте запрос менеджеру в свободной форме</p>
        <a href="/cart/" class="btn-get-an-account"><span class="icon"><svg class="icon">
                    <use xlink:href="#check-btn"></use>
                </svg></span>Получить счёт</a>
    </div>
</div>
""",
                              comment='Text block  with privilege club information.'
                              )


class Migration(migrations.Migration):

    dependencies = [
        ('statictext', '0006_agreement_text'),
    ]

    operations = [
        migrations.RunPython(create_text, ),
    ]
