# Generated by Django 2.2.11 on 2020-04-03 11:27

from django.db import migrations


def create_text(apps, schema_editor):
    Statictext = apps.get_model('statictext', 'Statictext')
    Statictext.objects.create(key='delivery_calc_page_text',
                              text='',
                              comment='Text for the delivery calculator page.'
                              )


class Migration(migrations.Migration):

    dependencies = [
        ('statictext', '0007_club_privileges_block'),
    ]

    operations = [
        migrations.RunPython(create_text, ),
    ]
