# Generated by Django 2.2.11 on 2020-04-08 11:05

from django.db import migrations


# OLD TEXT
# '<span class="copy">© 2020 Стройкер. Все права защищены</span>',


def create_footer_text(apps, schema_editor):
    Statictext = apps.get_model('statictext', 'Statictext')
    Statictext.objects.create(key='footer_text',
                              text='',
                              comment='Text for the site footer.'
                              )


class Migration(migrations.Migration):

    dependencies = [
        ('statictext', '0008_delivery_calc_page_text'),
    ]

    operations = [
        migrations.RunPython(create_footer_text, ),
    ]
