# Generated by Django 2.2.12 on 2020-04-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statictext', '0009_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='statictext',
            name='use_editor',
            field=models.BooleanField(default=False, verbose_name='use editor'),
        ),
        migrations.AlterField(
            model_name='statictext',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
    ]
