# Generated by Django 2.2.12 on 2020-05-31 12:59

from django.db import migrations

def create_statictext(app, schema):
    Statictext = app.get_model('statictext', 'Statictext')
    Statictext.objects.create(
        key='comparise_description',
        text='',
        comment='Text for product comparison page'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('statictext', '0010_auto_20200412_1719'),
    ]

    operations = [
        migrations.RunPython(create_statictext, ),
    ]
