# Generated by Django 2.2.20 on 2021-07-28 09:53

from django.db import migrations


def create_statictext(app, schema):
    Statictext = app.get_model('statictext', 'Statictext')
    Statictext.objects.create(
        key='text_about_payment_on_product_page',
        text="""
<ul>
    <li>— Картой / наличными при получении</li>
    <li>— Онлайн на сайте</li>
    <li>— Оплата в кредит</li>
    <li>— Безналом по счёту</li>
</ul>
<a href="/cart/" class="btn-get-an-account-min">
    <span class="icon">
        <svg class="icon">
            <use xlink:href="#check-btn"></use>
        </svg>
    </span>Получить счёт
</a>""",
        comment='Текст блока с информацией об оплате на странице товара.'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('statictext', '0011_comparise_description'),
    ]

    operations = [
        migrations.RunPython(create_statictext, ),
    ]
