# Generated by Django 2.2.26 on 2022-04-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statictext', '0013_alter_for_statictext_about_product_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='statictext',
            name='use_custom_form',
            field=models.BooleanField(default=False, help_text='Uses the custom form inside test.To insert the desired custom form use the syntax: {% custom_form "CUSTOM-FORM-KEY" %}', verbose_name='use custom form'),
        ),
    ]
