# Generated by Django 2.2.26 on 2022-04-27 12:21

from django.db import migrations


def create_statictext(app, schema):
    Statictext = app.get_model('statictext', 'Statictext')
    Statictext.objects.create(
        key='no_category_or_products_text',
        text='<p>Раздел находится на стадии заполнения.</p>',
        comment='Заглушка для страниц каталога с отсутсвующими категориями или товарами.'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('statictext', '0014_statictext_use_custom_form'),
    ]

    operations = [
        migrations.RunPython(create_statictext, ),
    ]
