# Generated by Django 3.2.20 on 2023-09-08 04:52

from django.db import migrations


def create_statictext(app, schema):
    Statictext = app.get_model('statictext', 'Statictext')
    Statictext.objects.create(
        key='product-card__extra-text',
        text='',
        comment='Текст после описания в карточке товара'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('statictext', '0015_no_category_or_products_text'),
    ]

    operations = [migrations.RunPython(create_statictext, reverse_code=migrations.RunPython.noop)]
