# Generated by Django 3.2.25 on 2024-12-12

from django.db import migrations

from stroykerbox.apps.catalog import CatalogStatictextKeys


def create_new(app, *args, **kwargs):
    Statictext = app.get_model('statictext', 'Statictext')
    for item in CatalogStatictextKeys:
        obj, created = Statictext.objects.get_or_create(
            key=item.value, defaults={'text': '', 'comment': item.description}  # type: ignore
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0090_product_is_mod_priority'),
        ('statictext', '0016_auto_20230908_0752'),
    ]

    operations = [
        migrations.RunPython(create_new, migrations.RunPython.noop),
    ]
