# Generated by Django 2.2.11 on 2020-04-08 11:05

from django.db import migrations


def create_cookie_modal(apps, schema_editor):
    Statictext = apps.get_model('statictext', 'Statictext')
    Statictext.objects.get_or_create(
        key='cookie-modal__text',
        defaults={'text': '', 'comment': 'Text for the cookie modal.'},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('statictext', '0017_task_13207'),
    ]

    operations = [
        migrations.RunPython(create_cookie_modal, migrations.RunPython.noop),
    ]
