# Generated by Django 3.2.25 on 2025-10-16

from django.db import migrations

KEY = 'partners_new_partner_btn'


def create_new(app, *args, **kwargs):
    """
    https://redmine.nastroyker.ru/issues/17193
    """
    Statictext = app.get_model('statictext', 'Statictext')
    Statictext.objects.get_or_create(
        key=KEY,
        defaults=dict(
            text='',
            comment='Кнопка "Стать партнером" на странице списка партнеров.',
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('statictext', '0018_cookie_modal'),
    ]

    operations = [
        migrations.RunPython(create_new, reverse_code=migrations.RunPython.noop)
    ]
