# Generated by Django 2.2.6 on 2019-10-02 22:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import smart_selects.db_fields
import sorl.thumbnail.fields


def make_defaults(app, schema):
    Uom = app.get_model('catalog', 'Uom')
    default_items = ['м2', 'м', 'лист', 'коробка', 'кг', 'дюйм', 'куб', 'бухта']
    for name in default_items:
        Uom.objects.create(name=name)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='имя')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='categories/images', verbose_name='image')),
                ('slug', models.SlugField(verbose_name='название-метка (Для URL)')),
                ('published', models.BooleanField(db_index=True, default=True, verbose_name='show on the site')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=128, null=True, verbose_name='seo title')),
                ('seo_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='seo title')),
                ('seo_h1', models.CharField(blank=True, max_length=256, null=True, verbose_name='seo h1')),
                ('seo_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='seo-text')),
                ('icon', models.FileField(blank=True, null=True, upload_to='categories/images/icons', verbose_name='icon in rubrics')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='имя')),
                ('slug', models.SlugField(unique=True)),
                ('data_type', models.CharField(choices=[('decimal', 'number'), ('str', 'string')], default='str', max_length=7, verbose_name='type')),
                ('widget', models.CharField(choices=[('radio', 'radiobutton'), ('checkbox', 'checkbox'), ('select', 'drop-down list'), ('range', 'range')], default='checkbox', max_length=10, verbose_name='widget')),
                ('expanded', models.BooleanField(default=False, verbose_name='allways expanded')),
            ],
            options={
                'verbose_name': 'parameter',
                'verbose_name_plural': 'parameters',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_str', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='value')),
                ('value_slug', models.SlugField(blank=True, verbose_name='название-метка (Для URL)')),
                ('seo_str', models.CharField(blank=True, max_length=255, null=True, verbose_name='alternative value (seo)')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.Parameter')),
            ],
            options={
                'verbose_name': 'parameter value',
                'verbose_name_plural': 'parameter values',
                'unique_together': {('parameter', 'value_str')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='имя')),
                ('sku', models.CharField(max_length=128, verbose_name='commodity item identifier')),
                ('third_party_code', models.CharField(blank=True, max_length=128, null=True, verbose_name='third-party system code')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='slug')),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='show on site')),
                ('price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True, verbose_name='price')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='old price')),
                ('price_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'econom'), (1, 'norma'), (2, 'premium')], null=True, verbose_name='price category')),
                ('availability', models.PositiveSmallIntegerField(choices=[(0, 'not available'), (1, 'few'), (2, 'medium'), (3, 'many')], db_index=True, default=0, verbose_name='availability status')),
                ('is_hit', models.BooleanField(db_index=True, default=False, verbose_name='is bestseller')),
                ('is_new', models.BooleanField(db_index=True, default=False, verbose_name='product is new')),
                ('is_sale', models.BooleanField(db_index=True, default=False, verbose_name='sale')),
                ('discounted', models.BooleanField(db_index=True, default=False, verbose_name='discounted')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='product description')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='product weight, kg')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='product volume, m3')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='product length, mm')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='product width, mm')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='product height, mm')),
                ('meta_description', models.TextField(blank=True, max_length=256, null=True, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=128, null=True, verbose_name='meta keywords')),
                ('seo_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='seo title')),
                ('seo_h1', models.CharField(blank=True, max_length=256, null=True, verbose_name='seo h1')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('category', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.Category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='имя')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related', to='catalog.Product', verbose_name='related product')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref', to='catalog.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'related product',
                'verbose_name_plural': 'related products',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='products/images', verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.Product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
            },
        ),
        migrations.CreateModel(
            name='ProductCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('file', models.FileField(blank=True, help_text='Select image or document', upload_to='product/certificates', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='catalog.Product')),
            ],
            options={
                'verbose_name': 'product certificate',
                'verbose_name_plural': 'product certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Uom', verbose_name='unit'),
        ),
        migrations.CreateModel(
            name='ProductProps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('slug', models.SlugField(max_length=255, verbose_name='название-метка (Для URL)')),
                ('value', models.CharField(max_length=2048, verbose_name='value')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='props', to='catalog.Product')),
            ],
            options={
                'verbose_name': 'product property',
                'verbose_name_plural': 'product properties',
                'ordering': ['position'],
                'unique_together': {('product', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductParameterValueMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_decimal_low', models.DecimalField(blank=True, db_index=True, decimal_places=2, default=None, help_text='Minimum or single numeric value', max_digits=8, null=True, verbose_name='min numerical value')),
                ('value_decimal_high', models.DecimalField(blank=True, db_index=True, decimal_places=2, default=None, help_text='Maximum numerical value', max_digits=8, null=True, verbose_name='max numerical value')),
                ('comment', models.TextField(blank=True, default='', verbose_name='comment')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Parameter')),
                ('parameter_value', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='parameter', chained_model_field='parameter', related_name='parameter_values', to='catalog.ParameterValue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
            options={
                'verbose_name': 'product parameter value',
                'verbose_name_plural': 'product parameter values',
                'ordering': ['position'],
                'unique_together': {('product', 'parameter')},
            },
        ),
        migrations.CreateModel(
            name='CategoryParameterMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(db_index=True, verbose_name='position')),
                ('display', models.BooleanField(default=False)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Parameter')),
            ],
            options={
                'verbose_name': 'category parameter',
                'verbose_name_plural': 'category parameters',
                'ordering': ['position'],
                'unique_together': {('category', 'parameter')},
                'index_together': {('category', 'parameter', 'display')},
            },
        ),
        migrations.RunPython(make_defaults),
    ]
