# Generated by Django 2.2.6 on 2019-10-03 09:23

from django.db import migrations, models
import django.db.models.deletion


def price_types_make_defaults(app, schema):
    PriceType = app.get_model('catalog', 'PriceType')
    default_items = ['эконом', 'норма', 'премиум']
    for name in default_items:
        PriceType.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='имя')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'price type',
                'verbose_name_plural': 'price types',
            },
        ),
        migrations.AlterModelOptions(
            name='uom',
            options={'verbose_name': 'unit', 'verbose_name_plural': 'units'},
        ),
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.PriceType', verbose_name='price type'),
        ),
        migrations.RunPython(price_types_make_defaults),
    ]
