# Generated by Django 2.2.6 on 2019-10-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191003_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_appearance_date',
            field=models.DateTimeField(blank=True, help_text='Optional. If currently not available.', null=True, verbose_name='stock appearance date'),
        ),
    ]
