# Generated by Django 2.2.6 on 2019-10-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_new_field_stock_appearance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='название-метка (Для URL)'),
        ),
    ]
