# Generated by Django 2.2.6 on 2019-10-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191007_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='stock name')),
                ('geo_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='latitude of the stock location', max_digits=9, null=True, verbose_name='latitude')),
                ('geo_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='longitude of the stock location', max_digits=9, null=True, verbose_name='longitude')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='ProductStockAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Stock')),
            ],
            options={
                'verbose_name': 'product availability in stock',
                'verbose_name_plural': 'product availability in stocks',
            },
        ),
    ]
