# Generated by Django 2.2.6 on 2019-10-09 16:34

from django.db import migrations, models


AVAILABILITY_STATUSES = (
    (0, 10, 'мало'),
    (11, 100, 'средне'),
    (101, 10000, 'много')
)


def create_initial_statuses(app, schema):
    ProductAvailabilityStatus = app.get_model(
        'catalog', 'ProductAvailabilityStatus')
    for range_from, range_to, name in AVAILABILITY_STATUSES:
        ProductAvailabilityStatus.objects.create(
            name=name,
            range_from=range_from,
            range_to=range_to
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productstockavailability_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAvailabilityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256,
                                          unique=True, verbose_name='имя')),
                ('range_from', models.PositiveIntegerField(
                    verbose_name='range from')),
                ('range_to', models.PositiveIntegerField(verbose_name='range to')),
            ],
        ),
        migrations.RunPython(create_initial_statuses),
    ]
