# Generated by Django 2.2.6 on 2019-10-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productavailabilitystatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productavailabilitystatus',
            options={'verbose_name': 'product availability status', 'verbose_name_plural': 'product availability statuses'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
    ]
