# Generated by Django 2.2.6 on 2019-10-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20191009_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_appearance_date',
            field=models.DateField(blank=True, help_text='Optional. If currently not available.', null=True, verbose_name='stock appearance date'),
        ),
    ]
