# Generated by Django 2.2.6 on 2019-10-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20191009_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='seo keywords'),
        ),
    ]
