# Generated by Django 2.2.6 on 2019-10-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20191014_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='meta keywords'),
        ),
    ]
