# Generated by Django 2.2.6 on 2019-10-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='address',
            field=models.CharField(default='', max_length=256, verbose_name='stock address'),
            preserve_default=False,
        ),
    ]
