# Generated by Django 2.2.6 on 2019-11-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_stock_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0, verbose_name='product weight, kg'),
        ),
    ]
