# Generated by Django 2.2.7 on 2019-11-09 12:46

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20191101_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_document',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='catalog_pro_search__ef5de3_gin'),
        ),
    ]
