# Generated by Django 2.2.7 on 2019-11-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20191109_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True, verbose_name='purchase price'),
        ),
    ]
