# Generated by Django 2.2.8 on 2019-12-10 10:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_product_purchase_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True, verbose_name='price')),
                ('created', models.DateField(db_index=True, default=datetime.datetime.today, verbose_name='created date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_prices', to='catalog.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'history price',
                'verbose_name_plural': 'history prices',
            },
        ),
    ]
