# Generated by Django 2.2.8 on 2019-12-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20191210_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_h1',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_text',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_h1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_title',
        ),
    ]
