# Generated by Django 2.2.9 on 2020-01-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20191227_1108'),
        ('catalog', '0018_stock_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLocationPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True, verbose_name='price')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='old price')),
                ('purchase_price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True, verbose_name='purchase price')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_prices', to='catalog.Product')),
            ],
            options={
                'verbose_name': 'location price',
                'verbose_name_plural': 'location prices',
                'unique_together': {('location', 'product')},
            },
        ),
    ]
