# Generated by Django 2.2.9 on 2020-01-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20191227_1108'),
        ('catalog', '0019_productlocationprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlocationprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update date'),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
