# Generated by Django 2.2.9 on 2020-01-13 10:28
import uuid

from django.db import migrations, models


def fill_empty_product_sku(app, schema):
    Product = app.get_model('catalog', 'Product')
    for product in Product.objects.all():
        if not product.sku:
            product.sku = uuid.uuid4()
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20191227_1108'),
        ('catalog', '0020_auto_20200110_1535'),
    ]

    operations = [
        # migrations.RunPython(fill_empty_product_sku),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(
                max_length=128, unique=True, verbose_name='commodity item identifier'),
        ),
        migrations.AlterUniqueTogether(
            name='productpricehistory',
            unique_together={('location', 'product')},
        ),
    ]
