# Generated by Django 2.2.9 on 2020-01-15 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20200113_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Unique identifier for the product.', max_length=128, unique=True, verbose_name='commodity item identifier'),
        ),
        migrations.AlterField(
            model_name='productparametervaluemembership',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='catalog.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='productstockavailability',
            unique_together={('product', 'warehouse')},
        ),
    ]
