# Generated by Django 2.2.9 on 2020-02-21 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20200115_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstockavailability',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_availability', to='catalog.Product'),
        ),
    ]
