# Generated by Django 2.2.11 on 2020-03-07 19:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20200221_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='seo text'),
        ),
    ]
