# Generated by Django 2.2.11 on 2020-03-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_category_seo_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productpricehistory',
            unique_together=set(),
        ),
    ]
