# Generated by Django 2.2.11 on 2020-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20200313_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='position'),
        ),
    ]
