# Generated by Django 2.2.11 on 2020-03-16 15:55

from django.db import migrations, models
import django.db.models.deletion



def create_sets(apps, schema_editor):
    ProductSet = apps.get_model('catalog', 'ProductSet')
    ProductSet.objects.create(
            key='set-one',
            title='Set One'
            )
    ProductSet.objects.create(
            key='set-two',
            title='Set Two'
            )

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20200316_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('key', models.SlugField(max_length=70, primary_key=True, serialize=False, verbose_name='key')),
                ('title', models.CharField(max_length=255, verbose_name='block title')),
            ],
            options={
                'verbose_name': 'product set',
                'verbose_name_plural': 'product sets',
            },
        ),
        migrations.CreateModel(
            name='ProductSetMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('published', models.BooleanField(default=True, verbose_name='show')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='catalog.Product')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.ProductSet')),
            ],
            options={
                'verbose_name': 'product in set',
                'verbose_name_plural': 'products in set',
                'ordering': ['position'],
            },
        ),
        migrations.RunPython(create_sets, ),
    ]
