# Generated by Django 2.2.11 on 2020-03-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20200318_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsetmembership',
            name='cols',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='number cols'),
        ),
        migrations.AddField(
            model_name='productsetmembership',
            name='rows',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='number rows'),
        ),
    ]
