# Generated by Django 2.2.11 on 2020-03-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_auto_20200319_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsetmembership',
            name='cols',
        ),
        migrations.RemoveField(
            model_name='productsetmembership',
            name='rows',
        ),
        migrations.AddField(
            model_name='productset',
            name='cols',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='number cols'),
        ),
        migrations.AddField(
            model_name='productset',
            name='rows',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='number rows'),
        ),
    ]
