# Generated by Django 2.2.11 on 2020-03-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_auto_20200319_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='productset',
            name='banners',
            field=models.BooleanField(default=False, verbose_name='show banners'),
        ),
    ]
