# Generated by Django 2.2.11 on 2020-03-24 16:30

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_productset_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='search_document',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
