# Generated by Django 2.2.11 on 2020-03-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20200324_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productset',
            name='cols',
        ),
    ]
