# Generated by Django 2.2.11 on 2020-03-28 15:49

from django.db import migrations, models


def proccess_categories(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    Category.objects.filter(level=0).update(is_container=True)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_remove_productset_cols'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_container',
            field=models.BooleanField(default=False, help_text='The category is a container for child categories.', verbose_name='is container'),
        ),
        migrations.RunPython(proccess_categories,),
    ]
