# Generated by Django 2.2.11 on 2020-04-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20200329_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='list_as_rows',
            field=models.BooleanField(default=False, help_text='Display a list of products of the category as rows. Otherwise, a products will be displayed as tiles.', verbose_name='show list as rows'),
        ),
    ]
