# Generated by Django 2.2.11 on 2020-04-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_auto_20200404_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcertificate',
            name='file',
            field=models.FileField(help_text='Select image or document', upload_to='product/certificates', verbose_name='file'),
        ),
    ]
