# Generated by Django 2.2.12 on 2020-04-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_auto_20200408_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='highlight',
            field=models.BooleanField(default=False, verbose_name='highlight this category'),
        ),
    ]
