# Generated by Django 2.2.12 on 2020-04-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_category_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_appearance_date',
        ),
        migrations.AddField(
            model_name='product',
            name='days_to_arrive',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional. The number of days through which the missing product will arrive at some warehouse.', null=True, verbose_name='days to arrive'),
        ),
    ]
