# Generated by Django 2.2.12 on 2020-10-13 16:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_auto_20200413_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='category',
            name='highlight',
            field=models.BooleanField(default=False, help_text='A flag indicating whether to highlight a category.', verbose_name='highlight this category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, help_text='The category icon to display on category list pages.', null=True, upload_to='categories/images/icons', verbose_name='icon in rubrics'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Category image.', null=True, upload_to='categories/images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Name of category.', max_length=70, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Parent category (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.Category', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.BooleanField(db_index=True, default=True, help_text='Category visibility status flag.', verbose_name='show on the site'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Formatted and optimized text to attract the attention of search engines.', null=True, verbose_name='seo text'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='URL-key', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='name',
            field=models.CharField(help_text='Name', max_length=32, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Product Category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Product description.', null=True, verbose_name='product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag: the product is discounted.', verbose_name='discounted'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.FloatField(blank=True, help_text='Product height (in mm).', null=True, verbose_name='product height, mm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_hit',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag: the product is popular.', verbose_name='is bestseller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag: the product is new.', verbose_name='product is new'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag: The product is participating in a sale.', verbose_name='sale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.FloatField(blank=True, help_text='Product length (in mm).', null=True, verbose_name='product length, mm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Product Name', max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='The old price of the product.', max_digits=12, null=True, verbose_name='old price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='The main price of the product.', max_digits=12, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.ForeignKey(blank=True, help_text='Type of product price (target price group).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.PriceType', verbose_name='price type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.BooleanField(db_index=True, default=False, help_text='Product visibility status flag.', verbose_name='show on site'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='The main purchase price of the product.', max_digits=12, null=True, verbose_name='purchase price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(blank=True, help_text='Unit of measurement for the product.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Uom', verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.FloatField(blank=True, help_text='Product volume (in m3).', null=True, verbose_name='product volume, m3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0, help_text='Product weight (in kg).', verbose_name='product weight, kg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.FloatField(blank=True, help_text='Product width (in mm).', null=True, verbose_name='product width, mm'),
        ),
        migrations.AlterField(
            model_name='productset',
            name='key',
            field=models.SlugField(help_text='The value should only consist of Latin letters, numbers, underscores or hyphens.', max_length=70, primary_key=True, serialize=False, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='address',
            field=models.CharField(help_text='Warehouse address.', max_length=256, verbose_name='stock address'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Warehouse location.', null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(help_text='The name of the warehouse.', max_length=255, verbose_name='stock name'),
        ),
        migrations.AlterField(
            model_name='uom',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='uom',
            name='name',
            field=models.CharField(help_text='Name', max_length=32, verbose_name='name'),
        ),
    ]
