# Generated by Django 2.2.12 on 2020-10-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_auto_20201013_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ('position', 'name'), 'verbose_name': 'parameter', 'verbose_name_plural': 'parameters'},
        ),
    ]
