# Generated by Django 2.2.12 on 2020-10-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_auto_20201013_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametervalue',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='position'),
        ),
    ]
