# Generated by Django 2.2.12 on 2020-11-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_parametervalue_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametervalue',
            options={'ordering': ['position'], 'verbose_name': 'parameter value', 'verbose_name_plural': 'parameter values'},
        ),
    ]
