# Generated by Django 2.2.17 on 2020-11-30 13:05

from django.db import migrations, models
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_auto_20201120_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position', 'id'], 'verbose_name': 'product image', 'verbose_name_plural': 'product images'},
        ),
        migrations.AddField(
            model_name='category',
            name='svg_image',
            field=models.FileField(blank=True, null=True, upload_to='categories/images', validators=[stroykerbox.apps.utils.validators.validator_svg], verbose_name='svg image'),
        ),
    ]
