# Generated by Django 2.2.17 on 2020-12-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_auto_20201130_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametervalue',
            options={'ordering': ['value_str'], 'verbose_name': 'parameter value', 'verbose_name_plural': 'parameter values'},
        ),
        migrations.AddField(
            model_name='stock',
            name='third_party_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='third-party system code'),
        ),
    ]
