# Generated by Django 2.2.19 on 2021-03-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_auto_20201228_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='pickup_point',
            field=models.BooleanField(default=True, verbose_name='available as pickup point'),
        ),
    ]
