# Generated by Django 2.2.19 on 2021-03-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_stock_pickup_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='related_categories',
            field=models.ManyToManyField(related_name='_category_related_categories_+',
                                         to='catalog.Category', verbose_name='related categories', blank=True),
        ),
    ]
