# Generated by Django 2.2.19 on 2021-03-11 17:56

from django.db import migrations
import mptt.fields


def category_to_categories(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    for p in Product.objects.filter(category__isnull=False):
        p.categories.add(p.category)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_category_related_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=mptt.fields.TreeManyToManyField(
                to='catalog.Category', verbose_name='categories'),
        ),
        migrations.RunPython(category_to_categories,),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=mptt.fields.TreeManyToManyField(
                to='catalog.Category', verbose_name='categories', related_name='products'),
        ),
    ]
