# Generated by Django 2.2.19 on 2021-03-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_auto_20210311_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='position'),
        ),
    ]
