# Generated by Django 2.2.19 on 2021-06-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_auto_20210317_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoySkladSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.SmallIntegerField(choices=[(0, 'price update'), (1, 'stock update')], verbose_name='operation type')),
                ('log', models.TextField(blank=True, null=True, verbose_name='log messages')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='sync summary')),
                ('start_dt', models.DateTimeField(verbose_name='start datetime')),
                ('end_dt', models.DateTimeField(verbose_name='end datetime')),
            ],
            options={
                'verbose_name': 'moy sklad sync log',
                'verbose_name_plural': 'moy sklad sync logs',
            },
        ),
    ]
