# Generated by Django 2.2.20 on 2021-06-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_moyskladsynclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='maybeinterested_block',
            field=models.BooleanField(default=False, verbose_name='show "you may be interested" block'),
        ),
    ]
