# Generated by Django 2.2.20 on 2021-07-02 18:16

from django.db import migrations, models


def set_expanded(apps, schema_editor):
    CategoryParameterMembership = apps.get_model(
        'catalog', 'CategoryParameterMembership')
    for param_membership in CategoryParameterMembership.objects.all():
        param_membership.expanded = param_membership.parameter.expanded
        param_membership.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_category_maybeinterested_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryparametermembership',
            name='expanded',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_expanded,),
    ]
