# Generated by Django 2.2.20 on 2021-07-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_categoryparametermembership_expanded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='expanded',
        ),
    ]
