# Generated by Django 2.2.20 on 2021-11-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0055_remove_parameter_expanded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstockavailability',
            name='available',
            field=models.FloatField(default=0),
        ),
    ]
