# Generated by Django 2.2.26 on 2022-01-31 15:15

from django.db import migrations


def fix_range_param_datatypes(apps, schema_editor):
    try:
        Parameter = apps.get_model('catalog', 'Parameter')
        Parameter.objects.filter(widget='range').exclude(
            data_type='decimal').update(data_type='decimal')
    except Exception:
        return


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0056_auto_20211116_1414'),
    ]

    operations = [
        migrations.RunPython(fix_range_param_datatypes,
                             migrations.RunPython.noop),
    ]
