# Generated by Django 2.2.26 on 2022-02-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_fix_data_types_for_range_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='related_categories',
            field=models.ManyToManyField(blank=True, to='catalog.Category', verbose_name='related categories'),
        ),
    ]
