# Generated by Django 2.2.26 on 2022-04-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_auto_20220204_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='third_party_code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='third-party system code'),
        ),
    ]
