# Generated by Django 3.2.13 on 2022-05-19 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0060_auto_20220513_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='online_discount',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Percentage discount for the category product price when buying it through the cart.', null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='online price discount'),
        ),
    ]
