# Generated by Django 3.2.13 on 2022-06-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0061_category_online_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametervalue',
            options={'ordering': ['position', 'value_str'], 'verbose_name': 'parameter value', 'verbose_name_plural': 'parameter values'},
        ),
    ]
