# Generated by Django 3.2.13 on 2022-09-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0063_productimage_has_watermarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sidebar_siblings',
            field=models.BooleanField(default=False, help_text='Instead of filters, display links to sibling categories in the sidebar on the category page.', verbose_name='show siblings in sidebar'),
        ),
    ]
