# Generated by Django 3.2.15 on 2022-09-20 09:21

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0064_category_sidebar_siblings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='related_categories',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='_catalog_category_related_categories_+', to='catalog.Category', verbose_name='related categories'),
        ),
    ]
