# Generated by Django 3.2.15 on 2022-10-13 13:34

from django.db import migrations
from stroykerbox.apps.catalog.models import ParameterValue


def set_slugs_if_not(apps, schema_editor):
    for p in ParameterValue.objects.filter(value_slug=''):
        try:
            p.save()
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0065_alter_category_related_categories'),
    ]

    operations = [
        migrations.RunPython(set_slugs_if_not, migrations.RunPython.noop)
    ]
