# Generated by Django 3.2.15 on 2022-10-18 10:48

from django.db import migrations, models


def decimal_high_to_value_decimal(apps, schema_editor):
    ProductParameterValueMembership = apps.get_model(
        'catalog', 'ProductParameterValueMembership')
    ProductParameterValueMembership.objects.filter(
        value_decimal_high__isnull=False).update(value_decimal=models.F('value_decimal_high'))


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0066_set_slug_for_empty_in_pavameter_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='productparametervaluemembership',
            name='value_decimal',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='numerical value'),
        ),
        migrations.RunPython(decimal_high_to_value_decimal,
                             migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='productparametervaluemembership',
            name='value_decimal_high',
        ),
        migrations.RemoveField(
            model_name='productparametervaluemembership',
            name='value_decimal_low',
        ),
    ]
