# Generated by Django 3.2.15 on 2022-10-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0067_remove_param_value_low_and_hight_to_value_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='yml_export',
            field=models.BooleanField(default=False, verbose_name='Export to YML'),
        ),
    ]
