# Generated by Django 3.2.15 on 2022-12-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0068_product_yml_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_from',
            field=models.BooleanField(default=False, help_text='Отображать цену товара с признаком "от".', verbose_name='price "from"'),
        ),
    ]
