# Generated by Django 3.2.15 on 2023-02-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0069_product_price_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='mode_widget',
            field=models.CharField(choices=[('button', 'button'), ('select', 'select')], default='button', help_text='Widget for displaying in product modifications.', max_length=6, verbose_name='modification widget'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='use_for_modes',
            field=models.BooleanField(default=False, help_text='Use as product modification property.', verbose_name='use for modifications'),
        ),
        migrations.AddField(
            model_name='product',
            name='modifications',
            field=models.ManyToManyField(related_name='_catalog_product_modifications_+', to='catalog.Product', verbose_name='modifications'),
        ),
    ]
