# Generated by Django 3.2.15 on 2023-03-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0070_auto_20230223_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='modifications',
        ),
        migrations.AddField(
            model_name='product',
            name='modification_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='modification code'),
        ),
    ]
