# Generated by Django 3.2.15 on 2023-04-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0071_auto_20230323_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='products_per_row',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Кол-во товаров в строке на странице категории.', null=True, verbose_name='кол-во товаров на строку'),
        ),
    ]
