# Generated by Django 3.2.15 on 2023-04-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0072_category_products_per_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='productset',
            name='products_per_row',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='кол-во товаров на строку'),
        ),
    ]
