# Generated by Django 3.2.15 on 2023-05-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0073_productset_products_per_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vk_group_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID группы товаров в VK.', null=True, verbose_name='vk-market group ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='vk_market',
            field=models.BooleanField(default=False, verbose_name='use for vk-market'),
        ),
    ]
