# Generated by Django 3.2.15 on 2023-06-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0074_auto_20230526_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_in_compete',
            field=models.BooleanField(default=False, help_text='Цена товара участвует в механизме конкуренции (проект "Мониторинг"). Т.е., заморожена от изменений, в том числе не меняется при подсчете онлайн-цены.', verbose_name='цена в "конкуренции"'),
        ),
    ]
