# Generated by Django 3.2.15 on 2023-06-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0075_product_price_in_compete'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='multiplicity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Multiplicity of packaging'),
        ),
    ]
