# Generated by Django 3.2.15 on 2023-06-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0076_product_multiplicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='multiplicity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Multiplicity of packaging'),
        ),
        migrations.AddField(
            model_name='product',
            name='multiplicity_label',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Multiplicity of packaginglabel'),
        ),
    ]
