# Generated by Django 3.2.20 on 2023-09-12 08:51

from django.db import migrations, models


def migrate_for_new(apps, schema_editor):
    ProductSet = apps.get_model('catalog', 'ProductSet')
    for s in ProductSet.objects.all():
        s.data_sm_rows = s.rows
        s.data_xl_slides = s.products_per_row

        s.save(update_fields=('data_sm_rows', 'data_xl_slides'))


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0078_auto_20230626_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='productset',
            name='data_lg_slides',
            field=models.PositiveSmallIntegerField(
                default=3, verbose_name='data-lg-slides'),
        ),
        migrations.AddField(
            model_name='productset',
            name='data_md_slides',
            field=models.PositiveSmallIntegerField(
                default=2, verbose_name='data-md-slides'),
        ),
        migrations.AddField(
            model_name='productset',
            name='data_slides',
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name='data-slides'),
        ),
        migrations.AddField(
            model_name='productset',
            name='data_sm_rows',
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name='data-sm-rows'),
        ),
        migrations.AddField(
            model_name='productset',
            name='data_xl_slides',
            field=models.PositiveSmallIntegerField(
                default=5, verbose_name='data-xl-slides'),
        ),
        migrations.RunPython(migrate_for_new, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='productset',
            name='products_per_row',
        ),
    ]
