# Generated by Django 3.2.20 on 2023-10-26 11:52

from django.db import migrations, models
import django.db.models.deletion
import stroykerbox.apps.utils.fields


def create_default_currency(apps, schema_editor):
    apps.get_model('catalog', 'Currency').objects.get_or_create(
        code='rub',
        defaults={
            'symbol': '₽',
            'rate': 1,
            'is_default': True
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0079_auto_20230912_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('code', stroykerbox.apps.utils.fields.LowerCaseCharField(
                    help_text='Трехбуквенный код валюты, соответсвующий ее обозначению в международной системе стандартов наименования.', max_length=3, unique=True, verbose_name='код валюты')),
                ('symbol', models.CharField(
                    max_length=8, verbose_name='символ валюты')),
                ('is_default', models.BooleanField(
                    default=False, verbose_name='валюта по-умолчанию')),
                ('rate', models.DecimalField(decimal_places=2,
                 help_text='Коэффициeнт, на который будут умножаться "не основные" валюты', max_digits=12, verbose_name='курс валюты')),
            ],
            options={
                'verbose_name': 'валюта',
                'verbose_name_plural': 'валюты',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='catalog.currency', verbose_name='валюта'),
        ),
        migrations.RunPython(create_default_currency,
                             migrations.RunPython.noop),
    ]
