# Generated by Django 3.2.20 on 2023-11-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0080_auto_20231026_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(related_name='_catalog_product_related_products_+', through='catalog.ProductRelated', to='catalog.Product'),
        ),
        migrations.AlterField(
            model_name='productprops',
            name='value',
            field=models.TextField(verbose_name='value'),
        ),
    ]
