# Generated by Django 3.2.20 on 2024-01-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0081_auto_20231128_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['position', 'price', '-updated_at'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='product',
            name='price_from_to',
            field=models.BooleanField(default=False, help_text='Отображать цену товара с признаком "от... до".', verbose_name='цена "от... до"'),
        ),
    ]
