# Generated by Django 3.2.20 on 2024-02-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0082_auto_20240111_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_action',
            field=models.BooleanField(db_index=True, default=False, help_text='Признак того, что товар участвует в акции.', verbose_name='акция'),
        ),
    ]
