# Generated by Django 3.2.20 on 2024-02-15

from django.db import migrations
from django.core.management import call_command


def upd_moy_sklad_api_url(apps, *args, **kwargs):
    call_command('constance', 'set', 'SYNC_API_URL',
                 'https://api.moysklad.ru/api/remap/1.2')


class Migration(migrations.Migration):

    dependencies = [
        ('constance', '0002_migrate_from_old_table'),
        ('catalog', '0083_product_is_action'),
    ]

    operations = [
        migrations.RunPython(upd_moy_sklad_api_url, migrations.RunPython.noop)
    ]
