# Generated by Django 3.2.25 on 2024-04-05
# https://redmine.fancymedia.ru/issues/11434

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0084_moy_sklad_api_upd'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description2',
            field=ckeditor.fields.RichTextField(
                blank=True, help_text='Дополнительное описание товара.', null=True, verbose_name='описание 2'),
        ),
    ]
