# Generated by Django 3.2.24 on 2024-04-19 06:08

from django.db import migrations, models
import django.db.models.deletion
import stroykerbox.apps.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0085_product_description2'),
    ]

    operations = [
        migrations.CreateModel(
            name='YmlCustomExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Категории'), (2, 'Товары')], verbose_name='Тип')),
                ('slug', stroykerbox.apps.utils.fields.SlugPreviewField(help_text='URL-key', verbose_name='slug')),
                ('categories', models.ManyToManyField(to='catalog.Category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Yml экспорт товаров',
                'verbose_name_plural': 'Yml экспорт товаров',
            },
        ),
        migrations.CreateModel(
            name='YmlCustomProductExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ymlcustomexport')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Экспорт продукта',
                'verbose_name_plural': 'Экспорт продуктов',
            },
        ),
    ]
