# Generated by Django 3.2.25 on 2024-05-09 14:04

from django.db import migrations, models
import stroykerbox.apps.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0086_ymlcustomexport_ymlcustomproductexport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ymlcustomexport',
            name='slug',
            field=stroykerbox.apps.utils.fields.SlugPreviewField(
                help_text='URL-key', unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='ymlcustomexport',
            name='categories',
            field=models.ManyToManyField(
                blank=True, to='catalog.Category', verbose_name='Категории'),
        ),
    ]
