# Generated by Django 3.2.25 on 2024-05-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0087_alter_ymlcustomexport_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='multiplicity_label',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Multiplicity of packaging label'),
        ),
    ]
