# Generated by Django 3.2.25 on 2024-06-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0088_alter_product_multiplicity_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='productset',
            name='data_sm_slides',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='data-sm-slides'),
        ),
    ]
