# Generated by Django 3.2.25 on 2024-07-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0089_productset_data_sm_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_mod_priority',
            field=models.BooleanField(default=False, help_text='Выводить в кач-ве приоритетного, если товары склеены.', verbose_name='приоритет в модификациях'),
        ),
    ]
