# Generated by Django 3.2.25 on 2024-12-13 13:55

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0090_product_is_mod_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(max_length=256, upload_to='products/images', verbose_name='image'),
        ),
    ]
