# Generated by Django 3.2.25 on 2025-01-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0091_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_file_size',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
