# Generated by Django 3.2.25 on 2025-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0092_productimage_image_file_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['position'], 'verbose_name': 'stock', 'verbose_name_plural': 'stocks'},
        ),
        migrations.AddField(
            model_name='stock',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='position'),
        ),
    ]
