# Generated by Django 3.2.25 on 2025-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0093_auto_20250627_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('position',), 'verbose_name': 'stock', 'verbose_name_plural': 'stocks'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('slug', 'level', 'parent'), name='unique_with_optional_parent'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('parent', None)), fields=('slug', 'level'), name='unique_without_optional_parent'),
        ),
    ]
