# Generated by Django 3.2.25 on 2025-08-18

from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0094_auto_20250627_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='use_editor',
            field=models.BooleanField(default=True, help_text='Использовать визуальный редактор для полей "описание" и "описание 2".', verbose_name='использовать редактор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=mptt.fields.TreeManyToManyField(help_text='Список категорий товара. При создании/обновлении через API нужно передавать список(массив) из ID нужных категорий.', related_name='products', to='catalog.Category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Product description.', null=True, verbose_name='product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description2',
            field=models.TextField(blank=True, help_text='Дополнительное описание товара.', null=True, verbose_name='описание 2'),
        ),
    ]
