# Generated by Django 2.2.7 on 2019-11-19 10:14

import ckeditor.fields
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('teaser', models.TextField(verbose_name='teaser text')),
                ('body', ckeditor.fields.RichTextField(verbose_name='article body')),
                ('label', models.CharField(help_text='Text label for article tagging.', max_length=60, verbose_name='label')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='news', verbose_name='image')),
                ('wide_view', models.BooleanField(default=True, verbose_name='wide view mode')),
                ('published', models.BooleanField(db_index=True, default=True, verbose_name='show on the site')),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-created', '-pk'],
            },
        ),
    ]
