# Generated by Django 2.2.7 on 2019-11-19 10:33

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='articles', verbose_name='image'),
        ),
    ]
