# Generated by Django 2.2.11 on 2020-04-06 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191119_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='updated',
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 18, 56, 45, 864795, tzinfo=utc), verbose_name='creation date'),
        ),
    ]
