# Generated by Django 2.2.11 on 2020-04-06 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200406_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='creation date'),
        ),
    ]
