# Generated by Django 2.2.11 on 2020-04-07 10:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200406_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='teaser',
            field=ckeditor.fields.RichTextField(verbose_name='teaser text'),
        ),
    ]
