# Generated by Django 2.2.19 on 2021-03-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_auto_20201228_1747'),
        ('articles', '0005_auto_20200407_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_products',
            field=models.ManyToManyField(to='catalog.Product', verbose_name='related products'),
        ),
        migrations.AddField(
            model_name='article',
            name='related_products_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title of the related products block'),
        ),
    ]
