# Generated by Django 2.2.19 on 2021-03-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210309_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='catalog.Product', verbose_name='related products'),
        ),
    ]
