# Generated by Django 2.2.7 on 2019-12-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('image', models.ImageField(upload_to='slides/big_slides', verbose_name='image')),
                ('content', models.TextField(blank=True, help_text='slide content', verbose_name='content')),
                ('url', models.CharField(blank=True, default='', help_text='Link URL', max_length=255, verbose_name='url')),
                ('published', models.BooleanField(db_index=True, default=True, verbose_name='published')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'big slide',
                'verbose_name_plural': 'big slides',
                'ordering': ['position'],
            },
        ),
    ]
