# Generated by Django 2.2.8 on 2019-12-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('published', models.BooleanField(db_index=True, default=True, verbose_name='published')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('logo', models.ImageField(upload_to='slides/partner_slides', verbose_name='partner logo')),
                ('url', models.URLField(blank=True, help_text='External Link URL', max_length=255, null=True, verbose_name='partner url')),
            ],
            options={
                'verbose_name': 'partner slide',
                'verbose_name_plural': 'partner slides',
                'ordering': ['position'],
            },
        ),
        migrations.AlterField(
            model_name='bigslide',
            name='content',
            field=models.TextField(blank=True, help_text='slide content', null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='bigslide',
            name='url',
            field=models.CharField(blank=True, help_text='Link URL', max_length=255, null=True, verbose_name='url'),
        ),
    ]
