# Generated by Django 2.2.11 on 2020-03-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0002_auto_20191210_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigslide',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='partnerslide',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='position'),
        ),
    ]
