# Generated by Django 2.2.11 on 2020-03-31 11:44

from django.db import migrations, models
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0003_auto_20200330_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bigslide',
            options={'ordering': ['-position'], 'verbose_name': 'big slide', 'verbose_name_plural': 'big slides'},
        ),
        migrations.AlterModelOptions(
            name='partnerslide',
            options={'ordering': ['-position'], 'verbose_name': 'partner slide', 'verbose_name_plural': 'partner slides'},
        ),
        migrations.AddField(
            model_name='bigslide',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='slides/big_slides/svg', validators=[stroykerbox.apps.utils.validators.validator_svg], verbose_name='svg image'),
        ),
        migrations.AddField(
            model_name='partnerslide',
            name='svg_logo',
            field=models.FileField(blank=True, null=True, upload_to='slides/partner_slides/svg', validators=[stroykerbox.apps.utils.validators.validator_svg], verbose_name='partner logo as svg'),
        ),
        migrations.AlterField(
            model_name='bigslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/big_slides', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='partnerslide',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='slides/partner_slides', verbose_name='partner logo'),
        ),
    ]
