# Generated by Django 2.2.12 on 2020-09-28 10:58

from django.db import migrations, models
import django.db.models.deletion
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0004_auto_20200331_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='key')),
                ('published', models.BooleanField(default=True, verbose_name='published')),
            ],
            options={
                'verbose_name': 'slide set',
                'verbose_name_plural': 'slide sets',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bigslide',
            options={'ordering': ['position'], 'verbose_name': 'big slide', 'verbose_name_plural': 'big slides'},
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('published', models.BooleanField(db_index=True, default=True, verbose_name='published')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/slides', verbose_name='image')),
                ('svg', models.FileField(blank=True, null=True, upload_to='slides/slides/svg', validators=[stroykerbox.apps.utils.validators.validator_svg], verbose_name='svg image')),
                ('content', models.TextField(blank=True, help_text='slide content', null=True, verbose_name='content')),
                ('url', models.CharField(blank=True, help_text='Link URL', max_length=255, null=True, verbose_name='url')),
                ('slide_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='slides.SlideSet')),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'slides',
                'ordering': ['position'],
            },
        ),
    ]
