# Generated by Django 2.2.12 on 2020-09-28 10:58

from logging import getLogger

from django.db import migrations, Error, transaction

logger = getLogger(__name__)


def create_slide_sets(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return
    try:
        slide_set_model = apps.get_model('slides.SlideSet')
        with transaction.atomic():
            slide_set_model.objects.update_or_create(key='slides_action_thumbs',
                                                     defaults={'name': 'Кнопки на главной странице'})
            slide_set_model.objects.update_or_create(key='big_slides_secondary',
                                                     defaults={'name': 'Второй набор слайдов на главной'})
    except Error as e:
        logger.error(str(e))


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0005_auto_20200928_1358'),
    ]

    operations = [
        migrations.RunPython(create_slide_sets, reverse_code=migrations.RunPython.noop),
    ]
