# Generated by Django 2.2.17 on 2021-03-05 10:54

from django.db import migrations, models
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0006_auto_20200928_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='url',
            field=models.CharField(blank=True, help_text='Link URL', max_length=255, null=True, validators=[stroykerbox.apps.utils.validators.url_or_path_validator], verbose_name='url'),
        ),
    ]
