# Generated by Django 2.2.20 on 2021-07-18 10:26

from django.db import migrations, models
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0007_auto_20210305_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigslide',
            name='url',
            field=models.CharField(blank=True, help_text='Link URL', max_length=255, null=True, validators=[stroykerbox.apps.utils.validators.url_or_path_validator], verbose_name='url'),
        ),
    ]
