# Generated by Django 2.2.26 on 2022-01-13 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0008_auto_20210718_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.DeleteModel(
            name='SlideSet',
        ),
    ]
