# Generated by Django 2.2.26 on 2022-01-14 09:43

from django.db import migrations, models
import django.db.models.deletion
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0009_auto_20220114_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='This value is used in the code. Do not touch it!', max_length=70, unique=True, verbose_name='key')),
                ('cols_num', models.PositiveSmallIntegerField(choices=[(2, 2), (3, 3), (6, 6)], verbose_name='cols in grid')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'slider set',
                'verbose_name_plural': 'slider sets',
            },
        ),
        migrations.CreateModel(
            name='SliderSetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/big_slides', verbose_name='image')),
                ('svg', models.FileField(blank=True, null=True, upload_to='slides/big_slides/svg', validators=[stroykerbox.apps.utils.validators.validator_svg], verbose_name='svg image')),
                ('url', models.CharField(blank=True, help_text='Link URL', max_length=255, null=True, validators=[stroykerbox.apps.utils.validators.url_or_path_validator], verbose_name='url')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text content')),
                ('img_open_full', models.BooleanField(default=False, verbose_name='open image in full size')),
                ('hide_adaptive', models.BooleanField(default=False, verbose_name='hide in adaptive')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('sliderset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliderset_items', to='slides.SliderSet')),
            ],
            options={
                'verbose_name': 'slider set item',
                'verbose_name_plural': 'slider set items',
                'ordering': ['position'],
            },
        ),
    ]
