# Generated by Django 2.2.26 on 2022-02-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0010_sliderset_slidersetitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderset',
            name='cols_num',
            field=models.PositiveSmallIntegerField(choices=[(2, 2), (3, 3), (4, 4), (6, 6)], verbose_name='cols in grid'),
        ),
    ]
