# Generated by Django 2.2.26 on 2022-02-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0011_auto_20220204_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderset',
            name='autoplay_timeout',
            field=models.PositiveIntegerField(default=5000, verbose_name='autoplay timeout, ms'),
        ),
        migrations.AddField(
            model_name='sliderset',
            name='use_autoplay',
            field=models.BooleanField(default=False, verbose_name='use autoplay'),
        ),
    ]
