# Generated by Django 2.2.26 on 2022-02-22 13:22

from django.db import migrations, models
import stroykerbox.apps.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0012_auto_20220217_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderset',
            name='arrow_left',
            field=models.FileField(blank=True, null=True, upload_to='slides/', validators=[stroykerbox.apps.utils.validators.validate_svg_or_image], verbose_name='left arrow'),
        ),
        migrations.AddField(
            model_name='sliderset',
            name='arrow_right',
            field=models.FileField(blank=True, null=True, upload_to='slides/', validators=[stroykerbox.apps.utils.validators.validate_svg_or_image], verbose_name='right arrow'),
        ),
    ]
