# Generated by Django 3.2.15 on 2023-02-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0013_auto_20220222_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigslide',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partnerslide',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sliderset',
            name='cols_num',
            field=models.PositiveSmallIntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], verbose_name='cols in grid'),
        ),
        migrations.AlterField(
            model_name='sliderset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slidersetitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
