# Generated by Django 3.2.15 on 2023-02-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0014_auto_20230202_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderset',
            name='zoom_effect',
            field=models.BooleanField(default=False, verbose_name='use zoom effect'),
        ),
    ]
