# Generated by Django 3.2.15 on 2023-02-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0015_sliderset_zoom_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderset',
            name='arrows_type',
            field=models.CharField(choices=[('arrows', 'стрелки сверху'), ('dots', 'точки снизу')], default='arrows', max_length=8, verbose_name='arrows type'),
        ),
    ]
