# Generated by Django 3.2.25 on 2024-06-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0016_sliderset_arrows_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderset',
            name='cols_num',
        ),
        migrations.AddField(
            model_name='sliderset',
            name='data_lg_slides',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='data-lg-slides'),
        ),
        migrations.AddField(
            model_name='sliderset',
            name='data_md_slides',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='data-md-slides'),
        ),
        migrations.AddField(
            model_name='sliderset',
            name='data_slides',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='data-slides'),
        ),
        migrations.AddField(
            model_name='sliderset',
            name='data_xl_slides',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='data-xl-slides'),
        ),
    ]
