# Generated by Django 3.2.25 on 2024-06-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0017_auto_20240619_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderset',
            name='data_rows',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='data-rows'),
        ),
        migrations.AddField(
            model_name='sliderset',
            name='data_sm_slides',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='data-sm-slides'),
        ),
    ]
